#+TITLE: Doom Emacs Config
#+AUTHOR: Ezequiel Cardoso
#+DESCRIPTION: personal Doom Emacs config.
#+HTML_HEAD: <style type="text/css">body{ max-width:50%; }</style>
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about-this-config][ABOUT THIS CONFIG]]
- [[#beacon][BEACON]]
- [[#bookmarks-and-buffers][BOOKMARKS AND BUFFERS]]
  - [[#bookmarks][Bookmarks]]
  - [[#buffers][Buffers]]
  - [[#global-auto-revert][Global Auto Revert]]
  - [[#keybindings-within-ibuffer-mode][Keybindings within ibuffer mode]]
- [[#calendar][CALENDAR]]
- [[#calibre][CALIBRE]]
- [[#clippy][CLIPPY]]
- [[#companytabnine][COMPANY/TABNINE]]
- [[#user-data][USER DATA]]
  - [[#configuring-user-data][Configuring User Data]]
- [[#dashboard][DASHBOARD]]
  - [[#configuring-dashboard][Configuring Dashboard]]
  - [[#dashboard-in-emacsclient][Dashboard in Emacsclient]]
- [[#dired][DIRED]]
  - [[#keybindings-to-open-dired][Keybindings To Open Dired]]
  - [[#keybindings-within-dired][Keybindings Within Dired]]
  - [[#keybindings-within-dired-with-peep-dired-mode-enabled][Keybindings Within Dired With Peep-Dired-Mode Enabled]]
  - [[#making-deleted-files-go-to-trash-can][Making deleted files go to trash can]]
- [[#doom-theme][DOOM THEME]]
- [[#elfeed][ELFEED]]
- [[#erc][ERC]]
- [[#evaluate-elisp-expressions][EVALUATE ELISP EXPRESSIONS]]
- [[#eww][EWW]]
- [[#fonts][FONTS]]
- [[#insert-date][INSERT DATE]]
- [[#ivy][IVY]]
  - [[#ivy-posframe][IVY-POSFRAME]]
  - [[#ivy-keybindings][IVY KEYBINDINGS]]
- [[#line-settings][LINE SETTINGS]]
- [[#magit][MAGIT]]
  - [[#mu4e][MU4E]]
- [[#nov][NOV]]
- [[#ollama][OLLAMA]]
- [[#neotree][NEOTREE]]
- [[#markdown][MARKDOWN]]
- [[#minimap][MINIMAP]]
- [[#modeline][MODELINE]]
- [[#mouse-support][MOUSE SUPPORT]]
- [[#lsp-company-backends][LSP-COMPANY-BACKENDS]]
- [[#open-specific-files][OPEN SPECIFIC FILES]]
- [[#org-mode][ORG MODE]]
- [[#org-modern][ORG-MODERN]]
- [[#org-capture][ORG CAPTURE]]
- [[#org-books][ORG-BOOKS]]
- [[#org-agenda][Org-Agenda]]
- [[#org-super-agenda][ORG SUPER AGENDA]]
- [[#notifications][NOTIFICATIONS]]
- [[#org-fonts][Org fonts]]
- [[#org-export][Org-export]]
- [[#org-journal][Org-journal]]
- [[#ox-hugo][Ox-Hugo]]
- [[#org-publish][Org-publish]]
- [[#org-roam][Org-roam]]
- [[#org-roam-ui][ORG-ROAM-UI]]
- [[#org-ref][ORG-REF]]
- [[#org-clock][ORG-CLOCK]]
- [[#org-contacts][ORG-CONTACTS]]
  - [[#org-auto-tangle][Org-auto-tangle]]
- [[#password-store][PASSWORD STORE]]
- [[#perspective][PERSPECTIVE]]
- [[#rainbow-mode][RAINBOW MODE]]
- [[#registers][REGISTERS]]
- [[#shells][SHELLS]]
- [[#spell-fu][SPELL-FU]]
- [[#splits][SPLITS]]
- [[#winner-mode][WINNER MODE]]
- [[#writeroom-mode][WRITEROOM MODE]]
- [[#zap-to-char][ZAP TO CHAR]]
- [[#python][PYTHON]]
- [[#php-configuration-with-intelephense][PHP Configuration with Intelephense]]
  - [[#lsp-configuration][LSP Configuration]]
  - [[#lsp-ui][LSP UI]]
  - [[#intelephense-configuration][Intelephense Configuration]]
  - [[#php-mode-hooks][PHP Mode Hooks]]
  - [[#company-configuration-for-php][Company Configuration for PHP]]
  - [[#flycheck-php-configuration][Flycheck PHP Configuration]]
  - [[#laravel-blade-configuration][Laravel Blade Configuration]]
  - [[#laravel-artisan-commands][Laravel Artisan Commands]]
  - [[#laravel-yasnippet-configuration][Laravel Yasnippet Configuration]]
  - [[#laravel-project-detection][Laravel Project Detection]]
  - [[#wordpress-configuration][WordPress Configuration]]
  - [[#wordpress-helper-functions][WordPress Helper Functions]]
  - [[#stubs-adicionales-laravel-wordpress-librerías-comunes][Stubs adicionales (Laravel, WordPress, librerías comunes)]]
  - [[#instalar-stubs-de-terceros-comandos-manuales-no-se-tanglean][Instalar stubs de terceros (comandos manuales, no se tanglean)]]
  - [[#configuración-específica-por-proyecto-referencia-no-se-tanglea][Configuración Específica por Proyecto (referencia, no se tanglea)]]
  - [[#crear-directorios-de-snippets-comando-manual-no-se-tanglea][Crear directorios de snippets (comando manual, no se tanglea)]]
  - [[#phpunit][PHPUnit]]
  - [[#composer][Composer]]
  - [[#soporte-para-archivos-env-laravel-etc][Soporte para archivos .env (Laravel, etc.)]]
  - [[#opcional-php-cs-fixer-al-guardar][[OPCIONAL] PHP-CS-Fixer al guardar]]
- [[#python-configuration-finance--jupyter][PYTHON CONFIGURATION (Finance / Jupyter)]]
  - [[#pyright--lsp][Pyright / LSP]]
  - [[#virtualenvs-con-pyvenv][Virtualenvs con pyvenv]]
  - [[#variables-de-entorno-env-con-direnv][Variables de entorno (.env) con direnv]]
  - [[#instalar-dependencias-dentro-del-venv-activo][Instalar dependencias dentro del venv activo]]
  - [[#jupyter-notebooks-kernels-reales][Jupyter notebooks (kernels reales)]]
  - [[#notebooks-estilo-celda-en-archivos-py--][Notebooks estilo celda en archivos .py (# %%)]]
  - [[#virtualenvs-con-pyvenv-1][Virtualenvs con pyvenv]]
  - [[#ein-emacs-ipython-notebook][EIN (Emacs IPython Notebook)]]
  - [[#cómo-usar-ein-ayuda-memoria][Cómo usar EIN (ayuda memoria)]]

* ABOUT THIS CONFIG
This is my personal Doom Emacs config.  Doom Emacs is a distribution of Emacs that uses the "evil" keybindings (Vim keybindings) and includes a number of nice extensions and a bit of configuration out of the box.  I am maintaining this config not just for myself, but also for those that want to explore some of what is possible with Emacs.  I will add a lot of examples of plugins and settings, some of them I may not even use personally.  I do this because many people following me on YouTube look at my configs as "documentation".

;; Declaramos las variables como nulas al inicio para que Emacs no tire error al leer el archivo
(defvar mu4e-headers-actions nil)
(defvar mu4e-view-actions nil)

* BEACON
Never lose your cursor.  When you scroll, your cursor will shine!  This is a global minor-mode. Turn it on everywhere with:

#+begin_src emacs-lisp
;; (beacon-mode 1)
#+end_src

* BOOKMARKS AND BUFFERS
Doom Emacs uses 'SPC b' for keybindings related to bookmarks and buffers.

** Bookmarks
Bookmarks are somewhat like registers in that they record positions you can jump to.  Unlike registers, they have long names, and they persist automatically from one Emacs session to the next. The prototypical use of bookmarks is to record where you were reading in various files.

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("b". "buffer")
       :desc "List bookmarks" "L" #'list-bookmarks
       :desc "Save current bookmarks to bookmark file" "w" #'bookmark-save))
#+end_src

** Buffers
Regarding /buffers/, the text you are editing in Emacs resides in an object called a /buffer/. Each time you visit a file, a buffer is used to hold the file’s text. Each time you invoke Dired, a buffer is used to hold the directory listing.  /Ibuffer/ is a program that lists all of your Emacs /buffers/, allowing you to navigate between them and filter them.

| COMMAND         | DESCRIPTION          | KEYBINDING |
|-----------------+----------------------+------------|
| ibuffer         | Launch ibuffer       | SPC b i    |
| kill-buffer     | Kill current buffer  | SPC b k    |
| next-buffer     | Goto next buffer     | SPC b n    |
| previous-buffer | Goto previous buffer | SPC b p    |
| save-buffer     | Save current buffer  | SPC b s    |

** Global Auto Revert
A buffer can get out of sync with respect to its visited file on disk if that file is changed by another program. To keep it up to date, you can enable Auto Revert mode by typing M-x auto-revert-mode, or you can set it to be turned on globally with 'global-auto-revert-mode'.  I have also turned on Global Auto Revert on non-file buffers, which is especially useful for 'dired' buffers.

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t)
#+end_src

** Keybindings within ibuffer mode
| COMMAND                           | DESCRIPTION                            | KEYBINDING |
|-----------------------------------+----------------------------------------+------------|
| ibuffer-mark-forward              | Mark the buffer                        | m          |
| ibuffer-unmark-forward            | Unmark the buffer                      | u          |
| ibuffer-do-kill-on-deletion-marks | Kill the marked buffers                | x          |
| ibuffer-filter-by-content         | Ibuffer filter by content              | f c        |
| ibuffer-filter-by-directory       | Ibuffer filter by directory            | f d        |
| ibuffer-filter-by-filename        | Ibuffer filter by filename (full path) | f f        |
| ibuffer-filter-by-mode            | Ibuffer filter by mode                 | f m        |
| ibuffer-filter-by-name            | Ibuffer filter by name                 | f n        |
| ibuffer-filter-disable            | Disable ibuffer filter                 | f x        |
| ibuffer-do-kill-lines             | Hide marked buffers                    | g h        |
| ibuffer-update                    | Restore hidden buffers                 | g H        |

#+begin_src emacs-lisp
(evil-define-key 'normal ibuffer-mode-map
  (kbd "f c") 'ibuffer-filter-by-content
  (kbd "f d") 'ibuffer-filter-by-directory
  (kbd "f f") 'ibuffer-filter-by-filename
  (kbd "f m") 'ibuffer-filter-by-mode
  (kbd "f n") 'ibuffer-filter-by-name
  (kbd "f x") 'ibuffer-filter-disable
  (kbd "g h") 'ibuffer-do-kill-lines
  (kbd "g H") 'ibuffer-update)
#+end_src

* CALENDAR
Let's make a 12-month calendar available so we can have a calendar app that, when we click on time/date in xmobar, we get a nice 12-month calendar to view.

This is a modification of: http://homepage3.nifty.com/oatu/emacs/calendar.html
See also: https://stackoverflow.com/questions/9547912/emacs-calendar-show-more-than-3-months

#+begin_src emacs-lisp
;; https://stackoverflow.com/questions/9547912/emacs-calendar-show-more-than-3-months
(defun dt/year-calendar (&optional year)
  (interactive)
  (require 'calendar)
  (let* (
      (current-year (number-to-string (nth 5 (decode-time (current-time)))))
      (month 0)
      (year (if year year (string-to-number (format-time-string "%Y" (current-time))))))
    (switch-to-buffer (get-buffer-create calendar-buffer))
    (when (not (eq major-mode 'calendar-mode))
      (calendar-mode))
    (setq displayed-month month)
    (setq displayed-year year)
    (setq buffer-read-only nil)
    (erase-buffer)
    ;; horizontal rows
    (dotimes (j 4)
      ;; vertical columns
      (dotimes (i 3)
        (calendar-generate-month
          (setq month (+ month 1))
          year
          ;; indentation / spacing between months
          (+ 5 (* 25 i))))
      (goto-char (point-max))
      (insert (make-string (- 10 (count-lines (point-min) (point-max))) ?\n))
      (widen)
      (goto-char (point-max))
      (narrow-to-region (point-max) (point-max)))
    (widen)
    (goto-char (point-min))
    (setq buffer-read-only t)))

(defun dt/scroll-year-calendar-forward (&optional arg event)
  "Scroll the yearly calendar by year in a forward direction."
  (interactive (list (prefix-numeric-value current-prefix-arg)
                     last-nonmenu-event))
  (unless arg (setq arg 0))
  (save-selected-window
    (if (setq event (event-start event)) (select-window (posn-window event)))
    (unless (zerop arg)
      (let* (
              (year (+ displayed-year arg)))
        (dt/year-calendar year)))
    (goto-char (point-min))
    (run-hooks 'calendar-move-hook)))

(defun dt/scroll-year-calendar-backward (&optional arg event)
  "Scroll the yearly calendar by year in a backward direction."
  (interactive (list (prefix-numeric-value current-prefix-arg)
                     last-nonmenu-event))
  (dt/scroll-year-calendar-forward (- (or arg 1)) event))

(map! :leader
      :desc "Scroll year calendar backward" "<left>" #'dt/scroll-year-calendar-backward
      :desc "Scroll year calendar forward" "<right>" #'dt/scroll-year-calendar-forward)

(defalias 'year-calendar 'dt/year-calendar)

 (setq org-icalendar-timezone "America/Argentina") ;; timezone
(setq calendar-week-start-day 1) ;; la semana empieza el lunes
(setq european-calendar-style t) ;; estilo europeo


 (setq calendar-holidays '((holiday-fixed 1 1 "Año Nuevo")
               (holiday-fixed 2 28 "Carnaval")
               (holiday-fixed 3 1 "Carnaval")
               (holiday-fixed 3 24 "Día de la Memoria")
               (holiday-fixed 4 1 "Día de los Veteranos y Caídos en la Guerra de las Malvinas")
               (holiday-fixed 4 14 "Jueves Santo")
               (holiday-fixed 4 15 "Viernes Santo")
               (holiday-fixed 5 1 "Dia del Trabajo")
               (holiday-fixed 5 25 "Día de la Revolución de Mayo")
               (holiday-fixed 6 17 "Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes")
               (holiday-fixed 6 20 "Paso a la Inmortalidad del Gral. Manuel Belgrano")
               (holiday-fixed 7 6 "Día de Córdoba")
               (holiday-fixed 7 9 "Día de la Independencia")
               (holiday-fixed 8 15 "Paso a la Inmortalidad del Gral. José de San Martín")
               (holiday-fixed 9 7 "Feriado con fines turísticos")
               (holiday-fixed 9 30 "Día de San Jerónimo")
               (holiday-fixed 10 10 "Día del Respeto a la Diversidad Cultural")
               (holiday-fixed 11 20 "Día de la Soberanía Nacional")
               (holiday-fixed 11 21 "Feriado con fines turísticos")
               (holiday-fixed 12 8 "Inmaculada Concepción de María")
               (holiday-fixed 12 9 "Feriado con fines turísticos")
               (holiday-fixed 12 25 "Navidad")
               ))

#+end_src


#+RESULTS:
| er/add-org-mode-expansions | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | org-auto-tangle-mode | org-clock-load | evil-collection-mu4e-org-set-header-to-normal-mode | +lookup--init-org-mode-handlers-h | (closure ((hook . org-mode-hook) (--dolist-tail--) t) (&rest _) (add-hook 'before-save-hook 'org-encrypt-entries nil t)) | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-fold-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | doom-disable-show-paren-mode-h | doom-disable-show-trailing-whitespace-h | +org-enable-auto-reformat-tables-h | +org-enable-auto-update-cookies-h | +org-make-last-point-visible-h | org-fancy-priorities-mode | org-superstar-mode | evil-org-mode | toc-org-enable | embrace-org-mode-hook | org-eldoc-load | +literate-enable-recompile-h |

* CALIBRE

#+begin_src emacs-lisp

(use-package calibredb
  :defer t
  :config
  (setq calibredb-root-dir "~/Documentos/EmacsCalibre/")
  (setq calibredb-database-file (expand-file-name "metadata.db" calibredb-root-dir))
  (setq calibredb-program "calibredb") 
  (setq calibredb-library-alist '(("~/Documentos/EmacsCalibre/" :name "EmacsCalibre")))
  
  ;; Corrección del visor: Usar find-file de manera segura
(setq calibredb-reader-program-config
        '((:format "pdf" :reader find-file)   ; Abre con pdf-tools si está activo
          (:format "epub" :reader find-file)  ; Abre con nov.el de forma nativa
          (:format "azw3" :reader find-file)  ; Abre con nov.el gracias al truco de unzip
          (:format "mobi" :reader system)))   ; MOBI sigue abriendo con el visor externo

;; --- OBLIGAR A EMACS A DETECTAR LOS ATAJOS ---
  :bind (:map calibredb-search-mode-map
              ("RET" . calibredb-find-file)        ; Fuerza a INTRO a abrir el libro
              ("<return>" . calibredb-find-file)   ; Variante para teclados gráficos
              ("s" . calibredb-search)             ; Fuerza a 's' a buscar
              ("/" . calibredb-search)))

#+end_src

#+RESULTS:

* CLIPPY
Gives us a popup box with "Clippy, the paper clip". You can make him say various things by calling 'clippy-say' function.  But the more useful functions of clippy are the two describe functions provided: 'clippy-describe-function' and 'clippy-describe-variable'.  Hit the appropriate keybinding while the point is over a function/variable to call it.  A popup with helpful clippy will appear, telling you about the function/variable (using describe-function and describe-variable respectively).

| COMMAND                  | DESCRIPTION                           | KEYBINDING |
|--------------------------+---------------------------------------+------------|
| clippy-describe-function | /Clippy describes function under point/ | SPC c h f  |
| clippy-describe-variable | /Clippy describes variable under point/ | SPC c h v  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("c h" . "Help info from Clippy")
       :desc "Clippy describes function under point" "f" #'clippy-describe-function
       :desc "Clippy describes variable under point" "v" #'clippy-describe-variable))

#+end_src

* COMPANY/TABNINE

#+begin_src emacs-lisp

;; (add-hook 'after-init-hook 'global-company-mode)
;; (require 'company-tabnine)
;; (add-to-list 'company-backends #'company-tabnine)
;; ;; Trigger completion immediately.
;; (setq company-idle-delay 0)

;; ;; Number the candidates (use M-1, M-2 etc to select completions).
;; (setq company-show-numbers t)
(after! company
(setq +lsp-company-backends '(company-capf :separate company-yasnippet company-tabnine))
  (setq company-show-numbers t)
  (setq company-idle-delay 0)
)
#+end_src

#+RESULTS:
: t

#+end_src
* USER DATA

** Configuring User Data
#+begin_src emacs-lisp
(setq user-full-name "Ezequiel Cardoso"
      user-mail-address "ezequielcardoso@gmail.com"
       calendar-latitude -31.417
       calendar-longitude -64.183
       calendar-location-name "Cordoba, Argentina")
#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

** Configuring Dashboard
#+begin_src emacs-lisp
(use-package dashboard
  :init      ;; tweak dashboard config before loading it
  (setq dashboard-set-heading-icons nil)
  (setq dashboard-set-file-icons nil)
  (setq dashboard-banner-logo-title "\nKEYBINDINGS:\
\nFind file               (SPC .)     \
Open buffer list    (SPC b i)\
\nFind recent files       (SPC f i)   \
Open the eshell     (SPC e s)\
\nOpen dired file manager (SPC d d)   \
List of keybindings (SPC h b b)")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.config/doom/doom-emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 10 )
                          (bookmarks . 5)
                          (projects . 5)
                          (registers . 5)))
  :config
  (dashboard-setup-startup-hook)
  (dashboard-modify-heading-icons '((recents . "file-text")
                                    (bookmarks . "book"))))
#+end_src

** Dashboard in Emacsclient
This setting ensures that emacsclient always opens on *dashboard* rather than *scratch*.
#+begin_src emacs-lisp
(setq doom-fallback-buffer-name "*dashboard*")
#+end_src

* DIRED
Dired is the file manager within Emacs.  Below, I setup keybindings for image previews (peep-dired).  Doom Emacs does not use 'SPC d' for any of its keybindings, so I've chosen the format of 'SPC d' plus 'key'.

** Keybindings To Open Dired

| COMMAND    | DESCRIPTION                        | KEYBINDING |
|------------+------------------------------------+------------|
| dired      | /Open dired file manager/            | SPC d d    |
| dired-jump | /Jump to current directory in dired/ | SPC d j    |

** Keybindings Within Dired
*** Basic dired commands

| COMMAND                 | DESCRIPTION                                 | KEYBINDING |
|-------------------------+---------------------------------------------+------------|
| dired-view-file         | /View file in dired/                          | SPC d v    |
| dired-up-directory      | /Go up in directory tree/                     | h          |
| dired-find-file         | /Go down in directory tree (or open if file)/ | l          |
| dired-next-line         | Move down to next line                      | j          |
| dired-previous-line     | Move up to previous line                    | k          |
| dired-mark              | Mark file at point                          | m          |
| dired-unmark            | Unmark file at point                        | u          |
| dired-do-copy           | Copy current file or marked files           | C          |
| dired-do-rename         | Rename current file or marked files         | R          |
| dired-hide-details      | Toggle detailed listings on/off             | (          |
| dired-git-info-mode     | Toggle git information on/off               | )          |
| dired-create-directory  | Create new empty directory                  | +          |
| dired-diff              | Compare file at point with another          | =          |
| dired-subtree-toggle    | Toggle viewing subtree at point             | TAB        |

*** Dired commands using regex

| COMMAND                 | DESCRIPTION                | KEYBINDING |
|-------------------------+----------------------------+------------|
| dired-mark-files-regexp | Mark files using regex     | % m        |
| dired-do-copy-regexp    | Copy files using regex     | % C        |
| dired-do-rename-regexp  | Rename files using regex   | % R        |
| dired-mark-files-regexp | Mark all files using regex | * %        |

*** File permissions and ownership

| COMMAND         | DESCRIPTION                      | KEYBINDING |
|-----------------+----------------------------------+------------|
| dired-do-chgrp  | Change the group of marked files | g G        |
| dired-do-chmod  | Change the mode of marked files  | M          |
| dired-do-chown  | Change the owner of marked files | O          |
| dired-do-rename | Rename file or all marked files  | R          |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("d" . "dired")
       :desc "Open dired" "d" #'dired
       :desc "Dired jump to current" "j" #'dired-jump)
      (:after dired
              (:map dired-mode-map
               :desc "Peep-dired image previews" "d p" #'peep-dired
               :desc "Dired view file" "d v" #'dired-view-file)))

(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file ; use dired-find-file instead of dired-open.
  (kbd "m") 'dired-mark
  (kbd "t") 'dired-toggle-marks
  (kbd "u") 'dired-unmark
  (kbd "C") 'dired-do-copy
  (kbd "D") 'dired-do-delete
  (kbd "J") 'dired-goto-file
  (kbd "M") 'dired-do-chmod
  (kbd "O") 'dired-do-chown
  (kbd "P") 'dired-do-print
  (kbd "R") 'dired-do-rename
  (kbd "T") 'dired-do-touch
  (kbd "Y") 'dired-copy-filenamecopy-filename-as-kill ; copies filename to kill ring.
  (kbd "+") 'dired-create-directory
  (kbd "-") 'dired-up-directory
  (kbd "% l") 'dired-downcase
  (kbd "% u") 'dired-upcase
  (kbd "; d") 'epa-dired-do-decrypt
  (kbd "; e") 'epa-dired-do-encrypt)
;; Get file icons in dired
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
;; With dired-open plugin, you can launch external programs for certain extensions
;; For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
(setq dired-open-extensions '(("gif" . "sxiv")
                              ("jpg" . "sxiv")
                              ("png" . "sxiv")
                              ("mkv" . "mpv")
                              ("mp4" . "mpv")))
#+end_src

** Keybindings Within Dired With Peep-Dired-Mode Enabled
If peep-dired is enabled, you will get image previews as you go up/down with 'j' and 'k'

| COMMAND              | DESCRIPTION                              | KEYBINDING |
|----------------------+------------------------------------------+------------|
| peep-dired           | /Toggle previews within dired/             | SPC d p    |
| peep-dired-next-file | /Move to next file in peep-dired-mode/     | j          |
| peep-dired-prev-file | /Move to previous file in peep-dired-mode/ | k          |

#+begin_src emacs-lisp
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
#+end_src

** Making deleted files go to trash can
#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t
      trash-directory "~/.local/share/Trash/files/")
#+end_src

* DOOM THEME
Setting the theme to doom-one.  To try out new themes, I set a keybinding for counsel-load-theme with 'SPC h t'.

#+begin_src emacs-lisp
(setq doom-theme 'doom-gruvbox-light)
(map! :leader
      :desc "Load new theme" "h t" #'consult-theme)
#+end_src

#+RESULTS:
: consult-theme

* ELFEED
An RSS newsfeed reader for Emacs.

#+begin_src emacs-lisp
(use-package elfeed
  :config
  ;; Sintaxis correcta para personalizar la cara de los feeds
  (setq elfeed-search-feed-face '(:foreground "#ffffff" :weight bold))  
  
  ;; Lista unificada de feeds RSS corregida y con paréntesis balanceados
  (setq elfeed-feeds
        '(;; --- EMACS, ORG-MODE & ORG-ROAM ---
          ("https://emacslife.com" emacs planet eng)
          ("https://sachachua.com" emacs tech eng)
          ("https://karthinks.com" emacs dev eng)
          ("https://protesilaos.com" emacs linux philosophy eng)
          
          ;; --- LINUX & ARCHLINUX ---
          ("https://archlinux.org" arch linux critical)
          ("https://itsfoss.com" linux tech eng)
          ("https://phoronix.com" linux hardware benchmarks eng)
          ("https://gamingonlinux.com" linux gaming eng)

          ;; --- FINANZAS (ARGENTINAS & MUNDIALES) ---
          ("https://cronista.com" finanzas argentina es)
          ("https://iprofesional.com" finanzas argentina es)
          ("https://ft.com" finanzas global eng)
          ("https://bloomberg.com" finanzas global eng)

          ;; --- TECNOLOGÍA & CULTURA HACKER ---
          ("https://ycombinator.com" tech hacker global eng)
          ("https://hnrss.org" tech hacker popular eng)
          ("https://ieee.org" tech ciencia eng)

          ;; --- JOURNALING, MINIMALISMO & PRODUCTIVIDAD ---
          ("https://zenhabits.net" journaling minimalismo eng)
          ("https://austinkleon.com" journaling creativity eng)

          ;; --- TEMÁTICA EXTRA: ITALIANO (TECNOLOGÍA Y LINUX) ---
          ("https://lffl.org" linux tech it)
          ("https://lealternative.net" tech software_libre it)
          
          ;; --- FEEDS COMPLEMENTARIOS ORIGINALES VERIFICADOS ---
          ("https://orgmode.org" emacs orgmode)
          ("https://desdelinux.net" linux blog es)
          ("https://elblogdelazaro.org" linux blog es)
          ("https://victorhckinthefreeworld.com" linux blog es)
          ("http://feedburner.com" linux podcast es)
          ("https://nueva-actitud.org" blog es)
          ("https://lukesmith.xyz" linux blog)
          ("https://linuxfoundation.org" linux)
          ("https://linux.com" linux)
          ("https://tecmint.com" linux dev)
          ("https://amitmerchant.com" dev blog)
          ("https://christoph-rumpel.com" dev php)
          ("https://dcblog.dev" dev php)
          ("https://phppot.com" dev php)
          ("https://tomasvotruba.com" dev php)
          ("https://stitcher.io" dev php))
)

  ;; Menú de marcadores guardados (Bookmarks) estructurado
  (setq elfeed-search-bookmarks
        '(("Finanzas Argentinas e Internacionales" "+finanzas +unread" ?f)
          ("Desarrollo de Software y PHP" "+dev +unread" ?d)
          ("Noticias Críticas de Linux y Arch" "+critical +unread" ?l)
          ("Todo lo no leído (Default)" "+unread" ?u)
          ("Todos los artículos (Historial)" "" ?a)))

  ;; Estirar ancho de columna para títulos largos
  (setq elfeed-search-title-max-width 100))

(use-package elfeed-goodies
  :init
  ;; 1. Desactivamos que elfeed-goodies intente alterar la cabecera rota
  (setq elfeed-goodies/alter-header nil)
  (elfeed-goodies/setup)
  :config
  (setq elfeed-goodies/entry-pane-size 0.5)
  
  ;; 2. REPARACIÓN FORZADA: Restauramos la cabecera nativa por defecto de Elfeed
  (setq elfeed-search-header-function #'elfeed-search-header))

(add-hook 'elfeed-search-mode-hook #'elfeed-update)

;; ATAJO GLOBAL (Estilo nativo de Doom Emacs)
(map! :leader
      :desc "Abrir Elfeed"
      "o R" #'elfeed) 

;; Mapeos Evil para navegar rápido con J y K en la interfaz dividida
(map! :map elfeed-show-mode-map
      :n "J" #'elfeed-goodies/split-show-next
      :n "K" #'elfeed-goodies/split-show-prev)

(map! :map elfeed-search-mode-map
      :n "J" #'elfeed-goodies/split-show-next
      :n "K" #'elfeed-goodies/split-show-prev)

;; Mapeos rápidos para filtrar por categorías (Bookmarks) con una sola tecla
(map! :map elfeed-search-mode-map
      :n "f" (λ! (elfeed-search-set-filter "+finanzas +unread"))   ; Presiona f para Finanzas
      :n "d" (λ! (elfeed-search-set-filter "+dev +unread"))        ; Presiona d para Programación
      :n "l" (λ! (elfeed-search-set-filter "+critical +unread"))   ; Presiona l para Avisos Críticos Arch
      :n "a" (λ! (elfeed-search-set-filter "")))                   ; Presiona a para Historial Completo

;; Asignación de la tecla 'R' (Mayúscula + R) para la captura directa e inteligente
(map! :map elfeed-show-mode-map   :n "R" #'my/elfeed-to-org-roam)
(map! :map elfeed-search-mode-map :n "R" #'my/elfeed-to-org-roam)
#+end_src
* ERC
ERC is a built-in Emacs IRC client.

| COMMAND | DESCRIPTION                                 | KEYBINDING |
|---------+---------------------------------------------+------------|
| erc-tls | /Launch ERC using more secure TLS connection/ | SPC e E    |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("e". "evaluate/ERC/EWW")
       :desc "Launch ERC with TLS connection" "E" #'erc-tls))

(setq erc-prompt (lambda () (concat "[" (buffer-name) "]"))
      erc-server "irc.libera.chat"
      erc-nick "cardosoe"
      erc-user-full-name "Ezequiel Cardoso"
      erc-track-shorten-start 24
      erc-autojoin-channels-alist '(("irc.libera.chat" "#archlinux" "#linux" "#emacs"))
      erc-kill-buffer-on-part t
      erc-fill-column 100
      erc-fill-function 'erc-fill-static
      erc-fill-static-center 20
      ;; erc-auto-query 'bury
      )

#+end_src

#+begin_src emacs-lisp
(after! elfeed
  ;; Define tus filtros rápidos personalizados
  (setq elfeed-search-bookmarks
        '(("Finanzas Argentinas e Internacionales" "+finanzas +unread" ?f)
          ("Desarrollo de Software y PHP" "+dev +unread" ?d)
          ("Noticias Críticas de Linux y Arch" "+critical +unread" ?l)
          ("Todo lo no leído (Default)" "+unread" ?u)
          ("Todos los artículos (Historial)" "" ?a)))

  ;; Atajos rápidos para activar los bookmarks con un solo botón en elfeed-search
  (map! :map elfeed-search-mode-map
        :n "f" (λ! (elfeed-search-set-filter "+finanzas +unread"))
        :n "d" (λ! (elfeed-search-set-filter "+dev +unread"))
        :n "l" (λ! (elfeed-search-set-filter "+critical +unread"))
        :n "a" (λ! (elfeed-search-set-filter ""))))
#+end_src


* EVALUATE ELISP EXPRESSIONS
Changing some keybindings from their defaults to better fit with Doom Emacs, and to avoid conflicts with my window managers which sometimes use the control key in their keybindings.  By default, Doom Emacs does not use 'SPC e' for anything, so I choose to use the format 'SPC e' plus 'key' for these (I also use 'SPC e' for 'eww' keybindings).

| COMMAND         | DESCRIPTION                                  | KEYBINDING |
|-----------------+----------------------------------------------+------------|
| eval-buffer     | /Evaluate elisp in buffer/                     | SPC e b    |
| eval-defun      | /Evaluate the defun containing or after point/ | SPC e d    |
| eval-expression | /Evaluate an elisp expression/                 | SPC e e    |
| eval-last-sexp  | /Evaluate elisp expression before point/       | SPC e l    |
| eval-region     | /Evaluate elisp in region/                     | SPC e r    |

#+Begin_src emacs-lisp
(map! :leader
      (:prefix ("e". "evaluate/ERC/EWW")
       :desc "Evaluate elisp in buffer" "b" #'eval-buffer
       :desc "Evaluate defun" "d" #'eval-defun
       :desc "Evaluate elisp expression" "e" #'eval-expression
       :desc "Evaluate last sexpression" "l" #'eval-last-sexp
       :desc "Evaluate elisp in region" "r" #'eval-region))
#+end_src

* EWW
EWW is the Emacs Web Wowser, the builtin browser in Emacs.  Below I set urls to open in a specific browser (eww) with browse-url-browser-function.  By default, Doom Emacs does not use 'SPC e' for anything, so I choose to use the format 'SPC e' plus 'key' for these (I also use 'SPC e' for 'eval' keybindings).  I chose to use 'SPC s w' for eww-search-words because Doom Emacs uses 'SPC s' for 'search' commands.

#+begin_src emacs-lisp
(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "firefox")
      ;;browse-url-generic-program "brave-browser.desktop")
;; (setq browse-url-browser-function 'eww-browse-url) ;
(map! :leader
      :desc "Search web for text between BEG/END"
      "s w" #'eww-search-words
      (:prefix ("e" . "evaluate/ERC/EWW")
       :desc "Eww web browser" "w" #'eww
       :desc "Eww reload page" "R" #'eww-reload))
#+end_src

* FONTS
Settings related to fonts within Doom Emacs:
+ 'doom-font' -- standard monospace font that is used for most things in Emacs.
+ 'doom-variable-pitch-font' -- variable font which is useful in some Emacs plugins.
+ 'doom-big-font' -- used in doom-big-font-mode; useful for presentations.
+ 'font-lock-comment-face' -- for comments.
+ 'font-lock-keyword-face' -- for keywords with special significance like 'setq' in elisp.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 15)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 15)
      doom-big-font (font-spec :family "JetBrains Mono" :size 20))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

* INSERT DATE
Some custom functions to insert the date.  The function 'insert-todays-date' can be used one of three different ways: (1) just the keybinding without the universal argument prefix, (2) with one universal argument prefix, or (3) with two universal argument prefixes.  The universal argument prefix is 'SPC-u' in Doom Emacs (C-u in standard GNU Emacs).  The function 'insert-any-date' only outputs to one format, which is the same format as 'insert-todays-date' without a prefix.

| COMMAND               | EXAMPLE OUTPUT            | KEYBINDING            |
|-----------------------+---------------------------+-----------------------|
| insert-todays-date | Friday, November 19, 2021 | SPC i d t             |
| insert-todays-date | 11-19-2021                | SPC u SPC i d t       |
| insert-todays-date | 2021-11-19                | SPC u SPC u SPC i d t |
| insert-any-date    | Friday, November 19, 2021 | SPC i d a             |

#+begin_src emacs-lisp
(defun dt/insert-todays-date (prefix)
  (interactive "P")
  (let ((format (cond
                 ((not prefix) "%A, %B %d, %Y")
                 ((equal prefix '(4)) "%m-%d-%Y")
                 ((equal prefix '(16)) "%Y-%m-%d"))))
    (insert (format-time-string format))))

(require 'calendar)
(defun insert-any-date (date)
  "Insert DATE using the current locale."
  (interactive (list (calendar-read-date)))
  (insert (calendar-date-string date)))

(map! :leader
      (:prefix ("i d" . "Insert date")
        :desc "Insert any date" "a" #'insert-any-date
        :desc "Insert todays date" "t" #'insert-todays-date))
#+end_src
* IVY
Ivy is a generic completion mechanism for Emacs.

** IVY-POSFRAME
Ivy-posframe is an ivy extension, which lets ivy use posframe to show its candidate menu.  Some of the settings below involve:
+ ivy-posframe-display-functions-alist -- sets the display position for specific programs
+ ivy-posframe-height-alist -- sets the height of the list displayed for specific programs

Available functions (positions) for 'ivy-posframe-display-functions-alist'
+ ivy-posframe-display-at-frame-center
+ ivy-posframe-display-at-window-center
+ ivy-posframe-display-at-frame-bottom-left
+ ivy-posframe-display-at-window-bottom-left
+ ivy-posframe-display-at-frame-bottom-window-center
+ ivy-posframe-display-at-point
+ ivy-posframe-display-at-frame-top-center

=NOTE:= If the setting for 'ivy-posframe-display' is set to 'nil' (false), anything that is set to 'ivy-display-function-fallback' will just default to their normal position in Doom Emacs (usually a bottom split).  However, if this is set to 't' (true), then the fallback position will be centered in the window.

#+begin_src emacs-lisp
(setq ivy-posframe-display-functions-alist
      '((swiper                     . ivy-posframe-display-at-point)
        (complete-symbol            . ivy-posframe-display-at-point)
        (counsel-M-x                . ivy-display-function-fallback)
        (counsel-esh-history        . ivy-posframe-display-at-window-center)
        (counsel-describe-function  . ivy-display-function-fallback)
        (counsel-describe-variable  . ivy-display-function-fallback)
        (counsel-find-file          . ivy-display-function-fallback)
        (counsel-recentf            . ivy-display-function-fallback)
        (counsel-register           . ivy-posframe-display-at-frame-bottom-window-center)
        (dmenu                      . ivy-posframe-display-at-frame-top-center)
        (nil                        . ivy-posframe-display))
      ivy-posframe-height-alist
      '((swiper . 20)
        (dmenu . 20)
        (t . 10)))
(ivy-posframe-mode 1) ; 1 enables posframe-mode, 0 disables it.
#+end_src

** IVY KEYBINDINGS
By default, Doom Emacs does not use 'SPC v', so the format I use for these bindings is 'SPC v' plus 'key'.

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("v" . "Ivy")
       :desc "Ivy push view" "v p" #'ivy-push-view
       :desc "Ivy switch view" "v s" #'ivy-switch-view))
#+end_src

* LINE SETTINGS
I set comment-line to 'SPC TAB TAB' which is a rather comfortable keybinding for me on my ZSA Moonlander keyboard.  The standard Emacs keybinding for comment-line is 'C-x C-;'.  The other keybindings are for commands that toggle on/off various line-related settings.  Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t' plus 'key' for those bindings.

| COMMAND                  | DESCRIPTION                               | KEYBINDING  |
|--------------------------+-------------------------------------------+-------------|
| comment-line             | /Comment or uncomment lines/                | SPC TAB TAB |
| hl-line-mode             | /Toggle line highlighting in current frame/ | SPC t h     |
| global-hl-line-mode      | /Toggle line highlighting globally/         | SPC t H     |
| doom/toggle-line-numbers | /Toggle line numbers/                       | SPC t l     |
| toggle-truncate-lines    | /Toggle truncate lines/                     | SPC t t     |

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative) ;;or t
(map! :leader
      :desc "Comment or uncomment lines" "TAB TAB" #'comment-line
      (:prefix ("t" . "toggle")
       :desc "Toggle line numbers" "l" #'doom/toggle-line-numbers
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle truncate lines" "t" #'toggle-truncate-lines))
#+end_src

* MAGIT
#+begin_src emacs-lisp
;;; tools/lsp/+lsp.el -*- lexical-binding: t; -*-

(defvar +lsp-company-backends
  (if (featurep! :editor snippets)
      '(:separate company-capf company-yasnippet)
    'company-capf)
  "The backends to prepend to `company-backends' in `lsp-mode' buffers.
Can be a list of backends; accepts any value `company-backends' accepts.")

(defvar +lsp-prompt-to-install-server t
  "If non-nil, prompt to install a server if no server is present.
If set to `quiet', suppress the install prompt and don't visibly inform the user
about it (it will be logged to *Messages* however).")

;;; Packages

(use-package! lsp-mode
  :commands lsp-install-server
  :init
  ;; Don't touch ~/.emacs.d, which could be purged without warning
  (setq lsp-session-file (concat doom-cache-dir "lsp-session")
        lsp-server-install-dir (concat doom-etc-dir "lsp"))
  ;; Don't auto-kill LSP server after last workspace buffer is killed, because I
  ;; will do it for you, after `+lsp-defer-shutdown' seconds.
  (setq lsp-keep-workspace-alive nil)

  ;; NOTE I tweak LSP's defaults in order to make its more expensive or imposing
  ;;      features opt-in. Some servers implement these poorly and, in most
  ;;      cases, it's safer to rely on Emacs' native mechanisms (eldoc vs
  ;;      lsp-ui-doc, open in popup vs sideline, etc).

  ;; Disable features that have great potential to be slow.
  (setq lsp-enable-folding nil
        lsp-enable-text-document-color nil)
  ;; Reduce unexpected modifications to code
  (setq lsp-enable-on-type-formatting nil)
  ;; Make breadcrumbs opt-in; they're redundant with the modeline and imenu
  (setq lsp-headerline-breadcrumb-enable nil)

  ;; Let doom bind the lsp keymap.
  (when (featurep! :config default +bindings)
    (setq lsp-keymap-prefix nil))

  :config
   (setq lsp-log-io t)

  (setq lsp-intelephense-storage-path (concat doom-etc-dir "lsp-intelephense/")
        lsp-vetur-global-snippets-dir
        (expand-file-name
         "vetur" (or (bound-and-true-p +snippets-dir)
                     (concat doom-private-dir "snippets/")))
        lsp-xml-jar-file (expand-file-name "org.eclipse.lsp4xml-0.3.0-uber.jar" lsp-server-install-dir)
        lsp-groovy-server-file (expand-file-name "groovy-language-server-all.jar" lsp-server-install-dir))

  ;; REVIEW Remove this once this is fixed upstream.
  (add-to-list 'lsp-client-packages 'lsp-racket)

  (add-hook! 'doom-escape-hook
    (defun +lsp-signature-stop-maybe-h ()
      "Close the displayed `lsp-signature'."
      (when lsp-signature-mode
        (lsp-signature-stop)
        t)))

  (set-popup-rule! "^\\*lsp-\\(help\\|install\\)" :size 0.35 :quit t :select t)
  (set-lookup-handlers! 'lsp-mode
    :definition #'+lsp-lookup-definition-handler
    :references #'+lsp-lookup-references-handler
    :documentation '(lsp-describe-thing-at-point :async t)
    :implementations '(lsp-find-implementation :async t)
    :type-definition #'lsp-find-type-definition)

  (defadvice! +lsp--respect-user-defined-checkers-a (fn &rest args)
    "Ensure user-defined `flycheck-checker' isn't overwritten by `lsp'."
    :around #'lsp-diagnostics-flycheck-enable
    (if flycheck-checker
        (let ((old-checker flycheck-checker))
          (apply fn args)
          (setq-local flycheck-checker old-checker))
      (apply fn args)))

  (add-hook! 'lsp-mode-hook
    (defun +lsp-display-guessed-project-root-h ()
      "Log what LSP things is the root of the current project."
      ;; Makes it easier to detect root resolution issues.
      (when-let (path (buffer-file-name (buffer-base-buffer)))
        (if-let (root (lsp--calculate-root (lsp-session) path))
            (lsp--info "Guessed project root is %s" (abbreviate-file-name root))
          (lsp--info "Could not guess project root."))))
    #'+lsp-optimization-mode)

  (when (featurep! :completion company)
    (add-hook! 'lsp-completion-mode-hook
      (defun +lsp-init-company-backends-h ()
        (when lsp-completion-mode
          (set (make-local-variable 'company-backends)
               (cons +lsp-company-backends
                     (remove +lsp-company-backends
                             (remq 'company-capf company-backends))))))))

  (defvar +lsp--deferred-shutdown-timer nil)
  (defadvice! +lsp-defer-server-shutdown-a (fn &optional restart)
    "Defer server shutdown for a few seconds.
This gives the user a chance to open other project files before the server is
auto-killed (which is a potentially expensive process). It also prevents the
server getting expensively restarted when reverting buffers."
    :around #'lsp--shutdown-workspace
    (if (or lsp-keep-workspace-alive
            restart
            (null +lsp-defer-shutdown)
            (= +lsp-defer-shutdown 0))
        (prog1 (funcall fn restart)
          (+lsp-optimization-mode -1))
      (when (timerp +lsp--deferred-shutdown-timer)
        (cancel-timer +lsp--deferred-shutdown-timer))
      (setq +lsp--deferred-shutdown-timer
            (run-at-time
             (if (numberp +lsp-defer-shutdown) +lsp-defer-shutdown 3)
             nil (lambda (workspace)
                   (with-lsp-workspace workspace
                     (unless (lsp--workspace-buffers workspace)
                       (let ((lsp-restart 'ignore))
                         (funcall fn))
                       (+lsp-optimization-mode -1))))
             lsp--cur-workspace))))

  ;; (defadvice! +lsp-dont-prompt-to-install-servers-maybe-a (fn &rest args)
  ;;   :around #'lsp
  ;;   (when (buffer-file-name)
  ;;     (require 'lsp-mode)
  ;;     (lsp--require-packages)
  ;;     (if (or (lsp--filter-clients
  ;;              (-andfn #'lsp--matching-clients?
  ;;                      #'lsp--server-binary-present?))
  ;;             (not (memq +lsp-prompt-to-install-server '(nil quiet))))
  ;;         (apply fn args)
  ;;       ;; HACK `lsp--message' overrides `inhibit-message', so use `quiet!'
  ;;       (let ((doom-debug-p
  ;;              (or doom-debug-p
  ;;                  (not (eq +lsp-prompt-to-install-server 'quiet)))))
  ;;         (doom-shut-up-a #'lsp--info "No language server available for %S"
  ;;                         major-mode)))))

  (when (featurep! :ui modeline +light)
    (defvar-local lsp-modeline-icon nil)

    (add-hook! '(lsp-before-initialize-hook
                 lsp-after-initialize-hook
                 lsp-after-uninitialized-functions
                 lsp-before-open-hook
                 lsp-after-open-hook)
      (defun +lsp-update-modeline (&rest _)
        "Update modeline with lsp state."
        (let* ((workspaces (lsp-workspaces))
               (face (if workspaces 'success 'warning))
               (label (if workspaces "LSP Connected" "LSP Disconnected")))
          (setq lsp-modeline-icon (concat
                                   " "
                                   (+modeline-format-icon 'faicon "rocket" "" face label -0.0575)
                                   " "))
          (add-to-list 'global-mode-string
                       '(t (:eval lsp-modeline-icon))
                       'append))))))


(use-package! lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :init
  (defadvice! +lsp--use-hook-instead-a (fn &rest args)
    "Change `lsp--auto-configure' to not force `lsp-ui-mode' on us. Using a hook
instead is more sensible."
    :around #'lsp--auto-configure
    (letf! ((#'lsp-ui-mode #'ignore))
      (apply fn args)))

  :config
  (when (featurep! +peek)
    (set-lookup-handlers! 'lsp-ui-mode
      :definition 'lsp-ui-peek-find-definitions
      :implementations 'lsp-ui-peek-find-implementation
      :references 'lsp-ui-peek-find-references
      :async t))

  (setq lsp-ui-peek-enable (featurep! +peek)
        lsp-ui-doc-max-height 8
        lsp-ui-doc-max-width 72         ; 150 (default) is too wide
        lsp-ui-doc-delay 0.75           ; 0.2 (default) is too naggy
        lsp-ui-doc-show-with-mouse nil  ; don't disappear on mouseover
        lsp-ui-doc-position 'at-point
        lsp-ui-sideline-ignore-duplicate t
        ;; Don't show symbol definitions in the sideline. They are pretty noisy,
        ;; and there is a bug preventing Flycheck errors from being shown (the
        ;; errors flash briefly and then disappear).
        lsp-ui-sideline-show-hover nil
        ;; Re-enable icon scaling (it's disabled by default upstream for Emacs
        ;; 26.x compatibility; see emacs-lsp/lsp-ui#573)
        lsp-ui-sideline-actions-icon lsp-ui-sideline-actions-icon-default)

  (map! :map lsp-ui-peek-mode-map
        "j"   #'lsp-ui-peek--select-next
        "k"   #'lsp-ui-peek--select-prev
        "C-k" #'lsp-ui-peek--select-prev-file
        "C-j" #'lsp-ui-peek--select-next-file))


(use-package! helm-lsp
  :when (featurep! :completion helm)
  :commands helm-lsp-workspace-symbol helm-lsp-global-workspace-symbol)


(use-package! lsp-ivy
  :when (featurep! :completion ivy)
  :commands lsp-ivy-workspace-symbol lsp-ivy-global-workspace-symbol)


(use-package! consult-lsp
  :defer t
  :when (featurep! :completion vertico)
  :init
  (map! :map lsp-mode-map [remap xref-find-apropos] #'consult-lsp-symbols))
#+end_src

** MU4E

#+begin_src emacs-lisp
;; 1. Cargar tu archivo de configuración modular SÓLO cuando mu4e se inicialice
(after! mu4e
  (condition-case err
      (load! "~/.config/mu4e/mu4e-config.el")
    (error (message "Error controlado al cargar mu4e-config: %s" (error-message-string err)))))
#+end_src

#+RESULTS:

*** ORG-MSG

#+begin_src emacs-lisp

;;; ==================================================================
;;; REDACCIÓN DE EMAILS EN ORG-MODE: ORG-MSG
;;; ==================================================================

(use-package! org-msg
  :after mu4e
  :config
  (setq org-msg-startup "hidestarsindent"
        org-msg-greeting-fmt "Hola %s,\n\n"
        org-msg-greeting-name-limit 3
        org-msg-default-alternatives '((html-and-text . (utf-8 utf-8)))
        org-msg-convert-uml-to-png nil
        ;; Tu firma personalizada con exportación HTML limpia
        org-msg-signature (concat
                           "#+begin_export html\n"
                           "<p>Saludos cordiales,<br />"
                           "<b>Ezequiel Cardoso</b></p>\n"
                           "#+end_export"))
  
  ;; Activar org-msg globalmente para que intercepte la edición de mensajes
  (org-msg-mode 1))

#+end_src
* NOV

#+begin_src emacs-lisp

(use-package nov
  :ensure t
  :defer t
  ;; Asocia tanto extensiones .epub como .azw3 al lector nativo
  :mode (("\\.epub\\'" . nov-mode)
         ("\\.azw3\\'" . nov-mode))
  :config
  (setq nov-text-width 80)
  
  ;; Truco para AZW3: Le dice a nov.el que use 'unzip' para abrirlos
  (add-to-list 'nov-associated-formats '("azw3" . unzip)))


#+end_src
* OLLAMA

#+begin_src emacs-lisp

(use-package! ellama
  :init
 (require 'llm-ollama)
 (setq ellama-language "Spanish")
  :config
  ;; Configurar el modelo de chat principal local (Llama 3.2 3B)
  (setq ellama-provider (make-llm-ollama :chat-model "llama3.2:3b" :embedding-model "nomic-embed-text"))
  
  ;; Definir tu directorio principal de Org-roam para la base de conocimientos
  (setq ellama-knowledge-database-directory "~/.org-roam-knowledge/")
  
  ;; Atajos de teclado corregidos con la macro oficial de Doom
  (map! :leader
        :prefix ("I" . "IA Local")
        :desc "Chatear con Ellama"        "c" #'ellama-chat
        :desc "Preguntar sobre región"    "p" #'ellama-ask-about
        :desc "Indexar una carpeta"       "i" #'ellama-context-add-directory
        :desc "Generar ideas de notas"    "g" #'ellama-generate-ideas))

;; Silenciador de advertencias estéticas menores
(setq warning-minimum-level :error)

#+end_src

#+RESULTS:
: :error


* NEOTREE
Neotree is a file tree viewer.  When you open neotree, it jumps to the current file thanks to neo-smart-open.  The neo-window-fixed-size setting makes the neotree width be adjustable.  Doom Emacs had no keybindings set for neotree.  Since Doom Emacs uses 'SPC t' for 'toggle' keybindings, I used 'SPC t n' for toggle-neotree.

| COMMAND        | DESCRIPTION               | KEYBINDING |
|----------------+---------------------------+------------|
| neotree-toggle | /Toggle neotree/            | SPC t n    |
| neotree- dir   | /Open directory in neotree/ | SPC d n    |

#+begin_src emacs-lisp
(after! neotree
  (setq neo-smart-open t
        neo-window-fixed-size nil))

(after! doom-themes
  (setq doom-neotree-enable-variable-pitch t)
  (doom-themes-neotree-config)) ; <- Esta línea activa los iconos de doom-themes en neotree

(map! :leader
      :desc "Toggle neotree file viewer" "t n" #'neotree-toggle
      :desc "Open directory in neotree" "d n" #'neotree-dir)
#+end_src

(after! neotree
  (setq neo-theme 'icons))


* MARKDOWN

#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.8))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.2)))))

#+end_src

* MINIMAP
A minimap sidebar displaying a smaller version of the current buffer on either the left or right side. It highlights the currently shown region and updates its position automatically.  Be aware that this minimap program does not work in Org documents.  This is not unusual though because I have tried several minimap programs and none of them can handle Org.

| COMMAND      | DESCRIPTION                               | KEYBINDING |
|--------------+-------------------------------------------+------------|
| minimap-mode | /Toggle minimap-mode/                       | SPC t m    |

#+begin_src emacs-lisp
(setq minimap-window-location 'right)
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Toggle minimap-mode" "m" #'minimap-mode))
#+end_src

* MODELINE
The modeline is the bottom status bar that appears in Emacs windows.  For more information on what is available to configure in the Doom modeline, check out:
https://github.com/seagle0128/doom-modeline

#+begin_src emacs-lisp
(set-face-attribute 'mode-line nil :font "Ubuntu Mono-13")
(setq doom-modeline-height 30     ;; sets modeline height
      doom-modeline-bar-width 5   ;; sets right bar width
      doom-modeline-persp-name t  ;; adds perspective name to modeline
      doom-modeline-persp-icon t) ;; adds folder icon next to persp name
#+end_src

* MOUSE SUPPORT
Adding mouse support in the terminal version of Emacs.

#+begin_src emacs-lisp
(xterm-mouse-mode 1)
#+end_src

* LSP-COMPANY-BACKENDS
#+begin_src emacs-lisp

(defvar +lsp-company-backends
  (if (featurep! :editor snippets)
      '(:separate company-capf company-yasnippet)
    'company-capf)
  "The backends to prepend to `company-backends' in `lsp-mode' buffers.
Can be a list of backends; accepts any value `company-backends' accepts.")

(defvar +lsp-prompt-to-install-server t
  "If non-nil, prompt to install a server if no server is present.
If set to `quiet', suppress the install prompt and don't visibly inform the user
about it (it will be logged to *Messages* however).")

;;; Packages

(use-package! lsp-mode
  :commands lsp-install-server
  :init
  ;; Don't touch ~/.emacs.d, which could be purged without warning
  (setq lsp-session-file (concat doom-cache-dir "lsp-session")
        lsp-server-install-dir (concat doom-etc-dir "lsp"))
  ;; Don't auto-kill LSP server after last workspace buffer is killed, because I
  ;; will do it for you, after `+lsp-defer-shutdown' seconds.
  (setq lsp-keep-workspace-alive nil)

  ;; NOTE I tweak LSP's defaults in order to make its more expensive or imposing
  ;;      features opt-in. Some servers implement these poorly and, in most
  ;;      cases, it's safer to rely on Emacs' native mechanisms (eldoc vs
  ;;      lsp-ui-doc, open in popup vs sideline, etc).

  ;; Disable features that have great potential to be slow.
  (setq lsp-enable-folding nil
        lsp-enable-text-document-color nil)
  ;; Reduce unexpected modifications to code
  (setq lsp-enable-on-type-formatting nil)
  ;; Make breadcrumbs opt-in; they're redundant with the modeline and imenu
  (setq lsp-headerline-breadcrumb-enable nil)

  ;; Let doom bind the lsp keymap.
  (when (featurep! :config default +bindings)
    (setq lsp-keymap-prefix nil))

  :config
  (setq lsp-log-io t)
  (setq lsp-intelephense-storage-path (concat doom-etc-dir "lsp-intelephense/")
        lsp-vetur-global-snippets-dir
        (expand-file-name
         "vetur" (or (bound-and-true-p +snippets-dir)
                     (concat doom-private-dir "snippets/")))
        lsp-xml-jar-file (expand-file-name "org.eclipse.lsp4xml-0.3.0-uber.jar" lsp-server-install-dir)
        lsp-groovy-server-file (expand-file-name "groovy-language-server-all.jar" lsp-server-install-dir))

  ;; REVIEW Remove this once this is fixed upstream.
  (add-to-list 'lsp-client-packages 'lsp-racket)

  (add-hook! 'doom-escape-hook
    (defun +lsp-signature-stop-maybe-h ()
      "Close the displayed `lsp-signature'."
      (when lsp-signature-mode
        (lsp-signature-stop)
        t)))

  (set-popup-rule! "^\\*lsp-\\(help\\|install\\)" :size 0.35 :quit t :select t)
  (set-lookup-handlers! 'lsp-mode
    :definition #'+lsp-lookup-definition-handler
    :references #'+lsp-lookup-references-handler
    :documentation '(lsp-describe-thing-at-point :async t)
    :implementations '(lsp-find-implementation :async t)
    :type-definition #'lsp-find-type-definition)

  (defadvice! +lsp--respect-user-defined-checkers-a (fn &rest args)
    "Ensure user-defined `flycheck-checker' isn't overwritten by `lsp'."
    :around #'lsp-diagnostics-flycheck-enable
    (if flycheck-checker
        (let ((old-checker flycheck-checker))
          (apply fn args)
          (setq-local flycheck-checker old-checker))
      (apply fn args)))

  (add-hook! 'lsp-mode-hook
    (defun +lsp-display-guessed-project-root-h ()
      "Log what LSP things is the root of the current project."
      ;; Makes it easier to detect root resolution issues.
      (when-let (path (buffer-file-name (buffer-base-buffer)))
        (if-let (root (lsp--calculate-root (lsp-session) path))
            (lsp--info "Guessed project root is %s" (abbreviate-file-name root))
          (lsp--info "Could not guess project root."))))
    #'+lsp-optimization-mode)

  (when (featurep! :completion company)
    (add-hook! 'lsp-completion-mode-hook
      (defun +lsp-init-company-backends-h ()
        (when lsp-completion-mode
          (set (make-local-variable 'company-backends)
               (cons +lsp-company-backends
                     (remove +lsp-company-backends
                             (remq 'company-capf company-backends))))))))

  (defvar +lsp--deferred-shutdown-timer nil)
  (defadvice! +lsp-defer-server-shutdown-a (fn &optional restart)
    "Defer server shutdown for a few seconds.
This gives the user a chance to open other project files before the server is
auto-killed (which is a potentially expensive process). It also prevents the
server getting expensively restarted when reverting buffers."
    :around #'lsp--shutdown-workspace
    (if (or lsp-keep-workspace-alive
            restart
            (null +lsp-defer-shutdown)
            (= +lsp-defer-shutdown 0))
        (prog1 (funcall fn restart)
          (+lsp-optimization-mode -1))
      (when (timerp +lsp--deferred-shutdown-timer)
        (cancel-timer +lsp--deferred-shutdown-timer))
      (setq +lsp--deferred-shutdown-timer
            (run-at-time
             (if (numberp +lsp-defer-shutdown) +lsp-defer-shutdown 3)
             nil (lambda (workspace)
                   (with-lsp-workspace workspace
                     (unless (lsp--workspace-buffers workspace)
                       (let ((lsp-restart 'ignore))
                         (funcall fn))
                       (+lsp-optimization-mode -1))))
             lsp--cur-workspace))))

  ;; (defadvice! +lsp-dont-prompt-to-install-servers-maybe-a (fn &rest args)
  ;;   :around #'lsp
  ;;   (when (buffer-file-name)
  ;;     (require 'lsp-mode)
  ;;     (lsp--require-packages)
  ;;     (if (or (lsp--filter-clients
  ;;              (-andfn #'lsp--matching-clients?
  ;;                      #'lsp--server-binary-present?))
  ;;             (not (memq +lsp-prompt-to-install-server '(nil quiet))))
  ;;         (apply fn args)
  ;;       ;; HACK `lsp--message' overrides `inhibit-message', so use `quiet!'
  ;;       (let ((doom-debug-p
  ;;              (or doom-debug-p
  ;;                  (not (eq +lsp-prompt-to-install-server 'quiet)))))
  ;;         (doom-shut-up-a #'lsp--info "No language server available for %S"
  ;;                         major-mode)))))

  (when (featurep! :ui modeline +light)
    (defvar-local lsp-modeline-icon nil)

    (add-hook! '(lsp-before-initialize-hook
                 lsp-after-initialize-hook
                 lsp-after-uninitialized-functions
                 lsp-before-open-hook
                 lsp-after-open-hook)
      (defun +lsp-update-modeline (&rest _)
        "Update modeline with lsp state."
        (let* ((workspaces (lsp-workspaces))
               (face (if workspaces 'success 'warning))
               (label (if workspaces "LSP Connected" "LSP Disconnected")))
          (setq lsp-modeline-icon (concat
                                   " "
                                   (+modeline-format-icon 'faicon "rocket" "" face label -0.0575)
                                   " "))
          (add-to-list 'global-mode-string
                       '(t (:eval lsp-modeline-icon))
                       'append))))))


(use-package! lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :init
  (defadvice! +lsp--use-hook-instead-a (fn &rest args)
    "Change `lsp--auto-configure' to not force `lsp-ui-mode' on us. Using a hook
instead is more sensible."
    :around #'lsp--auto-configure
    (letf! ((#'lsp-ui-mode #'ignore))
      (apply fn args)))

  :config
  (when (featurep! +peek)
    (set-lookup-handlers! 'lsp-ui-mode
      :definition 'lsp-ui-peek-find-definitions
      :implementations 'lsp-ui-peek-find-implementation
      :references 'lsp-ui-peek-find-references
      :async t))

  (setq lsp-ui-peek-enable (featurep! +peek)
        lsp-ui-doc-max-height 8
        lsp-ui-doc-max-width 72         ; 150 (default) is too wide
        lsp-ui-doc-delay 0.75           ; 0.2 (default) is too naggy
        lsp-ui-doc-show-with-mouse nil  ; don't disappear on mouseover
        lsp-ui-doc-position 'at-point
        lsp-ui-sideline-ignore-duplicate t
        ;; Don't show symbol definitions in the sideline. They are pretty noisy,
        ;; and there is a bug preventing Flycheck errors from being shown (the
        ;; errors flash briefly and then disappear).
        lsp-ui-sideline-show-hover nil
        ;; Re-enable icon scaling (it's disabled by default upstream for Emacs
        ;; 26.x compatibility; see emacs-lsp/lsp-ui#573)
        lsp-ui-sideline-actions-icon lsp-ui-sideline-actions-icon-default)

  (map! :map lsp-ui-peek-mode-map
        "j"   #'lsp-ui-peek--select-next
        "k"   #'lsp-ui-peek--select-prev
        "C-k" #'lsp-ui-peek--select-prev-file
        "C-j" #'lsp-ui-peek--select-next-file))


(use-package! helm-lsp
  :when (featurep! :completion helm)
  :commands helm-lsp-workspace-symbol helm-lsp-global-workspace-symbol)


(use-package! lsp-ivy
  :when (featurep! :completion ivy)
  :commands lsp-ivy-workspace-symbol lsp-ivy-global-workspace-symbol)


(use-package! consult-lsp
  :defer t
  :when (featurep! :completion vertico)
  :init
  (map! :map lsp-mode-map [remap xref-find-apropos] #'consult-lsp-symbols))
#+end_src

* OPEN SPECIFIC FILES
Keybindings to open files that I work with all the time using the find-file command, which is the interactive file search that opens with 'C-x C-f' in GNU Emacs or 'SPC f f' in Doom Emacs.  These keybindings use find-file non-interactively since we specify exactly what file to open.  The format I use for these bindings is 'SPC =' plus 'key' since Doom Emacs does not use 'SPC ='.

| PATH TO FILE                                                       | DESCRIPTION           | KEYBINDING |
|--------------------------------------------------------------------+-----------------------+------------|
| ~/Dropbox/Org/Agenda/agenda.org | /Edit agenda file/      | SPC = a    |
| ~/.config/doom/config.org"                                         | /Edit doom config.org/  | SPC = c    |
| ~/.config/doom/init.el"                                            | /Edit doom init.el/     | SPC = i    |
| ~/.config/doom/packages.el"                                        | /Edit doom packages.el/ | SPC = p    |
| ~/.config/doom/eshell/aliases"                                     | /Edit eshell aliases/   | SPC = e a  |
| ~/.config/doom/eshell/profile"                                     | /Edit eshell profile/   | SPC = e p  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("=" . "open file")
       :desc "Edit agenda file" "a" #'(lambda () (interactive) (find-file "~/Dropbox/Org/Agenda/agenda.org"))
       :desc "Edit doom config.org" "c" #'(lambda () (interactive) (find-file "~/.doom.d/config.org"))
       :desc "Edit doom init.el" "i" #'(lambda () (interactive) (find-file "~/.doom./init.el"))
       :desc "Edit doom packages.el" "p" #'(lambda () (interactive) (find-file "~/.doom./packages.el"))))
(map! :leader
      (:prefix ("= e" . "open eshell files")
       :desc "Edit eshell aliases" "a" #'(lambda () (interactive) (find-file "~/.config/doom/eshell/aliases"))
       :desc "Edit eshell profile" "p" #'(lambda () (interactive) (find-file "~/.config/doom/eshell/profile"))))
#+end_src

* ORG MODE
I wrapped most of this block in (after! org).  Without this, my settings might be evaluated too early, which will result in my settings being overwritten by Doom's defaults.  I have also enabled org-journal, org-superstar and org-roam by adding (+journal +pretty +roam2) to the org section of my Doom Emacs init.el.

=NOTE:= I have the location of my Org directory and Roam directory in $HOME/nc/ which is a Nextcloud folder that allows me to instantly sync all of my Org work between my home computer and my office computer.

#+begin_src emacs-lisp
(map! :leader
      :desc "Org babel tangle" "m B" #'org-babel-tangle)
(after! org
  (setq org-directory "~/Dropbox/Org/"
        org-agenda-files '("~/Dropbox/Org/Agenda")
        org-default-notes-file (expand-file-name "notes.org" org-directory)
        org-ellipsis " ▼ "
        org-superstar-headline-bullets-list '("◉" "●" "○" "◆" "●" "○" "◆")
        org-superstar-itembullet-alist '((?+ . ?➤) (?- . ?✦)) ; changes +/- symbols in item lists
        org-log-done 'time
        org-hide-emphasis-markers t
        ;; ex. of org-link-abbrev-alist in action
        ;; [[arch-wiki:Name_of_Page][Description]]
        org-link-abbrev-alist    ; This overwrites the default Doom org-link-abbrev-list
          '(("google" . "http://www.google.com/search?q=")
            ("arch-wiki" . "https://wiki.archlinux.org/index.php/")
            ("ddg" . "https://duckduckgo.com/?q=")
            ("wiki" . "https://en.wikipedia.org/wiki/"))
        org-table-convert-region-max-lines 20000
        org-todo-keywords        ; This overwrites the default Doom org-todo-keywords
          '((sequence
             "TODO(t)"           ; A task that is ready to be tackled
             "IDEA(i)"        ; Some ideas
             "PROJ(p)"           ; A project that contains other tasks
             "MAIL(m)"            ; Mails to read
             "WAIT(w)"           ; Something is holding up this task
             "|"                 ; The pipe necessary to separate "active" states and "inactive" states
             "DONE(d)"           ; Task has been completed
             "CANCELLED(c)" ))) ; Task has been cancelled

        ;; etiquetas que utilizo para mis notas
        (setq org-tag-alist '(
            ("@nota" . ?n)
            ("@casa" . ?c)
            ("@entrenamiento" . ?e)
            ("@fecha" . ?f)
            ("@salud" . ?s)
            ("@tarea" . ?t)
            ("@coche" . ?h)
            ("@trabajo" . ?t)
            ("@familia" .?F)
            ("@Zoe" . ?z)
            ("@Lucio" . ?l)
            ("@Linux" .?L)
            ("@proyecto" .?p)
            ("@blog" . ?b)
            ("@estudio" . ?E)
            ("@web" .?w)
            ("@mail" .?m)
            ("@desarrollo" . ?d)
            )))

#+end_src

* ORG-MODERN

#+begin_src emacs-lisp
(after! org
  (global-org-modern-mode))
(add-hook 'org-agenda-finalize-hook #'org-modern-agenda)

;; Minimal UI
(package-initialize)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
;; (modus-themes-load-modus)

;; Choose some fonts
;; (set-face-attribute 'default nil :family "Iosevka")
;; (set-face-attribute 'variable-pitch nil :family "Iosevka Aile")
;; (set-face-attribute 'org-modern-symbol nil :family "Iosevka")

;; Add frame borders and window dividers
(modify-all-frames-parameters
 '((right-divider-width . 40)
   (internal-border-width . 40)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))

(setq
 ;; Edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t

 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t
 org-agenda-tags-column 0)

;; Ellipsis styling
(setq org-ellipsis "…")
(set-face-attribute 'org-ellipsis nil :inherit 'default :box nil)

#+end_src

* ORG CAPTURE
#+begin_src emacs-lisp
;; (require 'mu4e-org)
;; (require 'org-mu4e)
(use-package org-capture
  :ensure nil
  :after org
  :bind ("C-c c" . org-capture)
  :preface
  (defvar my/org-meeting-template "* cita con %?
%T
:PROPERTIES:
:SUMMARY: %^{DESCRIPCION}
:NOMBRE: %^{NOMBRE}
:LUGAR: %^{DONDE}
:DIRECCION: %^{CALLE}
:TELEFONO: %^{123-456-789}
:NOTA: %^{NOTAS}
:AÑADIDA: %U
:END:
Fecha de la reunión: %T" "Plantilla para programar reuniones.")
  (defvar my/org-basic-task-template "* TODO %^{Tareas}
:PROPERTIES:
:Effort: %^{effort|1:00|0:05|0:15|0:30|2:00|4:00}
:END:
Capturado %<%Y-%m-%d %H:%M>" "Plantilla básica de tareas.")
  ;; Plantilla simplificada de contactos (sin org-contacts por ahora)
  (defvar my/org-contacts-template "* %^{Nombre}
:PROPERTIES:
:EMAIL: %^{Email}
:PHONE: %^{123-456-789}
:HOUSE: %^{123-456-789}
:ALIAS: %^{nuko}
:NICKNAME: %^{Carlos M}
:NOTE: %^{NOTA}
:ADDRESS: %^{Calle Ejemplo 1 2A, 28320, Pinto, Madrid, España}
:BIRTHDAY: %^{yyyy-mm-dd}
:END:" "Plantilla para contactos.")

  ;; Funciones auxiliares para el template de recetas
  (defun my/org-recipe-auto-tags (ingredientes)
    "Genera tags automáticos basados en ingredientes principales"
    (let ((tags-map '(("pollo" . "ave")
                     ("carne" . "carne")
                     ("pescado" . "pescado")
                     ("pasta" . "pasta")
                     ("arroz" . "arroz")
                     ("huevo" . "huevo")
                     ("queso" . "lacteo")
                     ("leche" . "lacteo")
                     ("tomate" . "verdura")
                     ("cebolla" . "verdura")
                     ("ajo" . "verdura")
                     ("chocolate" . "postre")
                     ("harina" . "panaderia")))
          (tags '()))
      (dolist (ingredient-tag tags-map)
        (when (string-match-p (car ingredient-tag) (downcase ingredientes))
          (push (cdr ingredient-tag) tags)))
      (string-join (delete-dups tags) ",")))

  (defun my/org-recipe-calculate-total-time (prep-time cook-time)
    "Calcula tiempo total sumando preparación y cocción"
    (let* ((prep-minutes (if (string-match "\\([0-9]+\\)" prep-time)
                            (string-to-number (match-string 1 prep-time)) 0))
           (cook-minutes (if (string-match "\\([0-9]+\\)" cook-time)
                            (string-to-number (match-string 1 cook-time)) 0))
           (total-minutes (+ prep-minutes cook-minutes)))
      (if (>= total-minutes 60)
          (format "%dh %dm" (/ total-minutes 60) (% total-minutes 60))
        (format "%dm" total-minutes))))

  ;; Plantilla avanzada para recetas compatible con Hugo
  (defvar my/org-recipe-template "* %^{Título de la receta}
:PROPERTIES:
:EXPORT_FILE_NAME: %^{nombre-archivo-sin-espacios}
:EXPORT_DATE: %<%Y-%m-%d>
:EXPORT_HUGO_SECTION: recetas
:EXPORT_HUGO_TAGS: %^{tags manuales (separados por comas)}
:EXPORT_HUGO_CATEGORIES: %^{categoría|desayuno|almuerzo|cena|postre|aperitivo|bebida|snack}
:DIFICULTAD: %^{dificultad|fácil|medio|difícil|experto}
:TIEMPO_PREP: %^{tiempo preparación (ej: 15 min)}
:TIEMPO_COCCION: %^{tiempo cocción (ej: 30 min)}
:TIEMPO_TOTAL: %(my/org-recipe-calculate-total-time prep-time cook-time)
:PORCIONES: %^{porciones (ej: 4)}
:CALORIAS: %^{calorías por porción (opcional)}
:CALORIAS_TOTAL: %^{calorías totales (opcional)}
:ORIGEN: %^{origen/región (opcional)}
:AUTOR: %^{autor de la receta}
:FUENTE: %^{fuente (libro, web, familia, etc.)}
:TIPO_PLATO: %^{tipo de plato|entrante|principal|postre|acompañamiento|bebida}
:METODO_COCCION: %^{método|horno|sartén|cocido|al vapor|frito|crudo|parrilla|microondas}
:ESTACION: %^{estación ideal|primavera|verano|otoño|invierno|todo el año}
:OCASION: %^{ocasión|diario|especial|festivo|rapido|batch cooking}
:RESTRICCIONES: %^{restricciones dietéticas|ninguna|vegetariano|vegano|sin gluten|sin lactosa|keto|paleo}
:ALERGENOS: %^{alérgenos principales|ninguno|gluten|lactosa|frutos secos|mariscos|huevo|soja}
:CONSERVACION: %^{conservación|nevera 3 días|congelador 3 meses|consumir inmediato}
:RATING: %^{calificación personal (1-5)|1|2|3|4|5}
:COSTO: %^{costo aproximado|bajo|medio|alto}
:FECHA_AÑADIDA: %U
:FECHA_ULTIMA_PREPARACION: %^{última vez preparada (yyyy-mm-dd)}
:VECES_PREPARADA: %^{veces preparada|1}
:RECETAS_RELACIONADAS: %^{recetas relacionadas (separadas por comas)}
:TAGS_AUTO: %(my/org-recipe-auto-tags ingredientes)
:ID: %(org-id-new)
:END:

 ** Resumen
%^{Resumen breve de la receta (1-2 líneas)}

 ** Ingredientes
%^{Lista de ingredientes (uno por línea con cantidad):
-
-
- }

 ** Instrucciones
%^{Pasos de preparación (numerados):
1.
2.
3. }

 ** Notas del Chef
%^{Consejos, trucos y variaciones}

 ** Historial de Preparación
 *** %<%Y-%m-%d> - Primera preparación
- Rating: %^{rating inicial}
- Notas: %^{notas de la primera preparación}
- Modificaciones: %^{cambios realizados}

 ** Variaciones
%^{Variaciones posibles de la receta}

 ** Maridaje
%^{Sugerencias de maridaje y acompañamiento}

 ** Equipamiento Necesario
%^{Utensilios y equipos necesarios}

 ** Fotografías
%^{Enlaces a fotografías o instrucciones para tomarlas}

 ** Etiquetas Automáticas
- Ingrediente principal: %(car (split-string ingredientes))
- Método: %^{método}
- Dificultad: %^{dificultad}
- Tiempo: %^{tiempo-total}

%?" "Plantilla avanzada para recetas compatible con Hugo.")
  :custom
  (org-capture-templates
   `(("c" "Contactos" entry (file+headline "~/Dropbox/Org/Agenda/contactos.org" "contactos")
      ,my/org-contacts-template
      :empty-lines 1)
     ("n" "Nota" entry (file+headline "~/Dropbox/Org/Agenda/nota.org" "nota")
      ,my/org-basic-task-template
      :empty-lines 1)
     ("i" "Cita" entry (file "~/Dropbox/Org/Agenda/citas.org")
      ,my/org-meeting-template
      :empty-lines 1)
     ("d" "Diario" entry (file+headline "~/Dropbox/Org/Agenda/diario.org" "diario")
      "* %U %?"
      :empty-lines 1)
     ("m" "Mail Follow Up" entry (file+olp "~/Dropbox/Org/Agenda/mail.org" "Follow Up")
      "* TODO Follow up with %:fromname on %a\nSCHEDULED:%t\n\n%i")
     ("M" "Mail Read Later" entry (file+olp "~/Dropbox/Org/Agenda/mail.org" "Read Later")
      "* TODO Read %:subject\nSCHEDULED:%t\n%a\n\n%i")
     ("w" "Ofertas Laborales" entry (file+olp "~/Dropbox/Org/Agenda/busquedaLaboral.org" "Ofertas laborales")
      "* TODO Follow up with %:fromname on %a\nSCHEDULED:%t\n\n%i")
     ("l" "Para leer" entry (file+headline "~/Dropbox/Org/Agenda/leer.org" "leer")
      ,my/org-basic-task-template
      :empty-lines 1)
     ("t" "Tarea" entry (file+headline "~/Dropbox/Org/Agenda/tareas.org" "tareas")
      ,my/org-basic-task-template
      :empty-lines 1)
     ;; Template avanzado para recetas
    ("r" "Receta Completa" entry (file "~/Dropbox/Org/Agenda/recetas.org")
         ,my/org-recipe-template
         :empty-lines 1)
     ;; Template rápido para recetas simples
    ("R" "Receta Rápida" entry (file "~/Dropbox/Org/Agenda/recetas.org")
         "* %^{Título}
:PROPERTIES:
:EXPORT_FILE_NAME: %^{nombre-archivo}
:EXPORT_DATE: %<%Y-%m-%d>
:EXPORT_HUGO_SECTION: recetas
:DIFICULTAD: %^{dificultad|fácil|medio|difícil}
:TIEMPO_PREP: %^{tiempo prep}
:TIEMPO_COCCION: %^{tiempo cocción}
:PORCIONES: %^{porciones}
:RATING: %^{rating|1|2|3|4|5}
:FECHA_AÑADIDA: %U
:END:

 ** Ingredientes
%^{ingredientes}

 ** Instrucciones
%^{instrucciones}

 ** Notas
%?"
         :empty-lines 1)
     )))

;; Funciones auxiliares para búsqueda y filtrado de recetas
(defun my/org-recipes-search-by-difficulty (level)
  "Busca recetas por nivel de dificultad"
  (interactive "sDificultad (fácil/medio/difícil): ")
  (org-tags-view nil (format "DIFICULTAD=\"%s\"" level)))

(defun my/org-recipes-search-by-time (max-time)
  "Busca recetas por tiempo máximo de preparación"
  (interactive "nTiempo máximo (minutos): ")
  (org-tags-view nil (format "TIEMPO_TOTAL<=%d" max-time)))

(defun my/org-recipes-search-by-rating (min-rating)
  "Busca recetas por calificación mínima"
  (interactive "nCalificación mínima (1-5): ")
  (org-tags-view nil (format "RATING>=%d" min-rating)))

(defun my/org-recipes-search-dietary-restrictions (restriction)
  "Busca recetas por restricciones dietéticas"
  (interactive "sRestricción (vegetariano/vegano/sin gluten): ")
  (org-tags-view nil (format "RESTRICCIONES=\"%s\"" restriction)))

(defun my/org-recipes-update-preparation-count ()
  "Actualiza el contador de veces preparada una receta"
  (interactive)
  (save-excursion
    (org-back-to-heading)
    (let* ((current-count (or (org-entry-get (point) "VECES_PREPARADA") "0"))
           (new-count (1+ (string-to-number current-count))))
      (org-entry-put (point) "VECES_PREPARADA" (number-to-string new-count))
      (org-entry-put (point) "FECHA_ULTIMA_PREPARACION" (format-time-string "%Y-%m-%d"))
      (message "Receta preparada %d veces. Última preparación: %s"
               new-count (format-time-string "%Y-%m-%d")))))

;; Configuración de agenda personalizada para recetas
(setq org-agenda-custom-commands
      '(("r" . "Recetas")
        ("rt" "Recetas por hacer" tags "TODO=\"TODO\"")
        ("rf" "Recetas fáciles" tags "DIFICULTAD=\"fácil\"")
        ("rr" "Recetas mejor valoradas" tags "RATING>=4")
        ("rq" "Recetas rápidas" tags "TIEMPO_TOTAL<=30")
        ("rv" "Recetas vegetarianas" tags "RESTRICCIONES=\"vegetariano\"")
        ("rn" "Recetas nuevas" tags "FECHA_AÑADIDA>=\"<-30d>\"")))

;; Keybindings para funciones de recetas
(global-set-key (kbd "C-c r s") 'my/org-recipes-search-by-difficulty)
(global-set-key (kbd "C-c r t") 'my/org-recipes-search-by-time)
(global-set-key (kbd "C-c r r") 'my/org-recipes-search-by-rating)
(global-set-key (kbd "C-c r d") 'my/org-recipes-search-dietary-restrictions)
(global-set-key (kbd "C-c r u") 'my/org-recipes-update-preparation-count)
      #+end_src

        #+RESULTS:
        : org-capture

* ORG-BOOKS

#+begin_src emacs-lisp
(require 'org-books)

;; Set path to the reading list org file
(setq org-books-file "~/Dropbox/Org/libros.org")

#+end_src

#+RESULTS:
| b | Book | entry | (file some-file.org) | %(let* ((url (substring-no-properties (current-kill 0))) |


#+RESULTS:

* Org-Agenda
#+begin_src emacs-lisp
;; (add-to-list 'load-path "~/.doom.d/lisp/elegant-agenda-mode")
;; (require 'elegant-agenda-mode)
;; (add-hook 'org-agenda-mode-hook 'elegant-agenda-mode)
;; (use-package org-agenda-property)
(setq org-agenda-files (quote
                    ("~/Dropbox/Org/Agenda/personal.org"
 			       "~/Dropbox/Org/Agenda/agenda.org"
 			       "~/Dropbox/Org/Agenda/mail.org"
 			       "~/Dropbox/Org/Agenda/trabajo.org"
 			       "~/Dropbox/Org/Journal/journal.org"
 			       "~/Dropbox/Org/Agenda/busquedaLaboral.org"
 			       "~/Dropbox/Org/Agenda/blog.org"
 			       "~/Dropbox/Org/Agenda/tareas.org"
 			       "~/Dropbox/Org/Agenda/citas.org"
 			       "~/Dropbox/Org/Agenda/familia.org"
 			       "~/Dropbox/Org/Agenda/reubicar.org"
 			       "~/Dropbox/Org/Agenda/diario.org"
 			       "~/Dropbox/Org/Agenda/gtasks/personal.org"
 			       "~/Dropbox/Org/Agenda/list.org"
 			       "~/Dropbox/Org/Roam/20220812195203-estudio.org"
                )))
#+end_src

* ORG SUPER AGENDA

#+begin_src emacs-lisp
(use-package org-super-agenda
  :after org-agenda
  :init
   (setq org-agenda-skip-scheduled-if-done t
      org-agenda-skip-deadline-if-done t
      org-agenda-include-deadlines t
      org-agenda-include-diary t
      org-agenda-block-separator nil
      org-agenda-compact-blocks t
      org-agenda-start-with-log-mode t
      org-super-agenda-groups '((:name "Today"
                                  :time-grid t
                                  :scheduled today)
                           (:name "Due today"
                                  :deadline today)
                           (:name "Important"
                                  :priority "A")
                           (:name "Overdue"
                                  :deadline past)
                           (:name "Due soon"
                                  :deadline future)
                           (:name "Big Outcomes"
                                  :tag "bo")))
  :config
  (org-super-agenda-mode))
#+end_src

#+RESULTS:
: t

* NOTIFICATIONS

#+begin_src emacs-lisp
 (require 'appt)
 (appt-activate 1)

 (use-package notifications
   :demand t)
 (add-hook 'org-finalize-agenda-hook 'org-agenda-to-appt) ;; update appt list on agenda view

 (setq appt-display-format 'window
       appt-message-warning-time '5)
(setq appt-disp-window-function
      (lambda (nmins curtime msg)
	(notifications-notify :title "Recordatorio!!"
			      :body (format "Tienes una cita %s en %d minutos" msg (string-to-number nmins))
			      :app-name "Emacs: Org"
			      :sound-name "alarm-clock-elapsed")))
(display-time)                   ;; activate time display
(run-at-time "24:01" 3600 'org-agenda-to-appt)           ;; update appt list hourly
(setq org-agenda-finalize-hook 'org-agenda-to-appt)

#+end_src

#+RESULTS:
: org-agenda-to-appt

* Org fonts
I have created an interactive function for each color scheme (M-x org-colors-*).  These functions will set appropriate colors and font attributes for org-level fonts and the org-table font.
#+begin_src emacs-lisp

;; (defun org-colors-doom-one ()
;;   "Enable Doom One colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#51afef" ultra-bold)
;;          (org-level-2 1.6 "#c678dd" extra-bold)
;;          (org-level-3 1.5 "#98be65" bold)
;;          (org-level-4 1.4 "#da8548" semi-bold)
;;          (org-level-5 1.3 "#5699af" normal)
;;          (org-level-6 1.2 "#a9a1e1" normal)
;;          (org-level-7 1.1 "#46d9ff" normal)
;;          (org-level-8 1.0 "#ff6c6b" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-dracula ()
;;   "Enable Dracula colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#8be9fd" ultra-bold)
;;          (org-level-2 1.6 "#bd93f9" extra-bold)
;;          (org-level-3 1.5 "#50fa7b" bold)
;;          (org-level-4 1.4 "#ff79c6" semi-bold)
;;          (org-level-5 1.3 "#9aedfe" normal)
;;          (org-level-6 1.2 "#caa9fa" normal)
;;          (org-level-7 1.1 "#5af78e" normal)
;;          (org-level-8 1.0 "#ff92d0" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-gruvbox-dark ()
;;   "Enable Gruvbox Dark colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#458588" ultra-bold)
;;          (org-level-2 1.6 "#b16286" extra-bold)
;;          (org-level-3 1.5 "#98971a" bold)
;;          (org-level-4 1.4 "#fb4934" semi-bold)
;;          (org-level-5 1.3 "#83a598" normal)
;;          (org-level-6 1.2 "#d3869b" normal)
;;          (org-level-7 1.1 "#d79921" normal)
;;          (org-level-8 1.0 "#8ec07c" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-monokai-pro ()
;;   "Enable Monokai Pro colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#78dce8" ultra-bold)
;;          (org-level-2 1.6 "#ab9df2" extra-bold)
;;          (org-level-3 1.5 "#a9dc76" bold)
;;          (org-level-4 1.4 "#fc9867" semi-bold)
;;          (org-level-5 1.3 "#ff6188" normal)
;;          (org-level-6 1.2 "#ffd866" normal)
;;          (org-level-7 1.1 "#78dce8" normal)
;;          (org-level-8 1.0 "#ab9df2" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-nord ()
;;   "Enable Nord colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#81a1c1" ultra-bold)
;;          (org-level-2 1.6 "#b48ead" extra-bold)
;;          (org-level-3 1.5 "#a3be8c" bold)
;;          (org-level-4 1.4 "#ebcb8b" semi-bold)
;;          (org-level-5 1.3 "#bf616a" normal)
;;          (org-level-6 1.2 "#88c0d0" normal)
;;          (org-level-7 1.1 "#81a1c1" normal)
;;          (org-level-8 1.0 "#b48ead" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-oceanic-next ()
;;   "Enable Oceanic Next colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#6699cc" ultra-bold)
;;          (org-level-2 1.6 "#c594c5" extra-bold)
;;          (org-level-3 1.5 "#99c794" bold)
;;          (org-level-4 1.4 "#fac863" semi-bold)
;;          (org-level-5 1.3 "#5fb3b3" normal)
;;          (org-level-6 1.2 "#ec5f67" normal)
;;          (org-level-7 1.1 "#6699cc" normal)
;;          (org-level-8 1.0 "#c594c5" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-palenight ()
;;   "Enable Palenight colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#82aaff" ultra-bold)
;;          (org-level-2 1.6 "#c792ea" extra-bold)
;;          (org-level-3 1.5 "#c3e88d" bold)
;;          (org-level-4 1.4 "#ffcb6b" semi-bold)
;;          (org-level-5 1.3 "#a3f7ff" normal)
;;          (org-level-6 1.2 "#e1acff" normal)
;;          (org-level-7 1.1 "#f07178" normal)
;;          (org-level-8 1.0 "#ddffa7" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-solarized-dark ()
;;   "Enable Solarized Dark colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#268bd2" ultra-bold)
;;          (org-level-2 1.6 "#d33682" extra-bold)
;;          (org-level-3 1.5 "#859900" bold)
;;          (org-level-4 1.4 "#b58900" semi-bold)
;;          (org-level-5 1.3 "#cb4b16" normal)
;;          (org-level-6 1.2 "#6c71c4" normal)
;;          (org-level-7 1.1 "#2aa198" normal)
;;          (org-level-8 1.0 "#657b83" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-solarized-light ()
;;   "Enable Solarized Light colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#268bd2" ultra-bold)
;;          (org-level-2 1.6 "#d33682" extra-bold)
;;          (org-level-3 1.5 "#859900" bold)
;;          (org-level-4 1.4 "#b58900" semi-bold)
;;          (org-level-5 1.3 "#cb4b16" normal)
;;          (org-level-6 1.2 "#6c71c4" normal)
;;          (org-level-7 1.1 "#2aa198" normal)
;;          (org-level-8 1.0 "#657b83" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; (defun org-colors-tomorrow-night ()
;;   "Enable Tomorrow Night colors for Org headers."
;;   (interactive)
;;   (dolist
;;       (face
;;        '((org-level-1 1.7 "#81a2be" ultra-bold)
;;          (org-level-2 1.6 "#b294bb" extra-bold)
;;          (org-level-3 1.5 "#b5bd68" bold)
;;          (org-level-4 1.4 "#e6c547" semi-bold)
;;          (org-level-5 1.3 "#cc6666" normal)
;;          (org-level-6 1.2 "#70c0ba" normal)
;;          (org-level-7 1.1 "#b77ee0" normal)
;;          (org-level-8 1.0 "#9ec400" normal)))
;;     (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
;;     (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; ;; Load our desired org-colors-* theme on startup
;; ;; (org-colors-doom-one)

#+end_src
* Org-export
We need ox-man for "Org eXporting" to manpage format.

=NOTE:= I also enable ox-publish for converting an Org site into an HTML site, but that is done in init.el (org +publish).

#+begin_src emacs-lisp
(use-package ox-man)
(use-package ox-hugo
;;  :ensure t   ;Auto-install the package from Melpa
;;  :pin melpa
;;  :after ox
  )
#+end_src

* Org-journal
#+begin_src emacs-lisp
(setq org-journal-dir "~/Dropbox/Org/Journal/journal.org/"
      org-journal-date-prefix "* "
      org-journal-time-prefix "** "
      org-journal-date-format "%B %d, %Y (%A) "
      org-journal-file-format "%Y-%m-%d.org")
#+end_src

* Ox-Hugo

#+begin_src emacs-lisp
;; Populates only the EXPORT_FILE_NAME property in the inserted heading.
(with-eval-after-load 'org-capture
  (defun org-hugo-new-subtree-post-capture-template ()
    "Returns `org-capture' template string for new Hugo post.
See `org-capture-templates' for more information."
    (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
           (fname (org-hugo-slug title)))
      (mapconcat #'identity
                 `(
                   ,(concat "* TODO " title)
                   ":PROPERTIES:"
                   ,(concat ":EXPORT_FILE_NAME: " fname)
                   ":END:"
                   "%?\n")          ;Place the cursor here finally
                 "\n"))))

#+end_src

* Org-publish
#+begin_src emacs-lisp
(setq org-publish-use-timestamps-flag nil)
(setq org-export-with-broken-links t)
(setq org-publish-project-alist
      '(("distro.tube"
         :base-directory "~/nc/gitlab-repos/distro.tube/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/"
         :recursive t
         :exclude "org-html-themes/.*"
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("org-static"
         :base-directory "~/Dropbox/Org/website/"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
         :publishing-directory "~/Dropbox/Org/website/public_html/"
         :recursive t
         :exclude ".*/org-html-themes/.*"
         :publishing-function org-publish-attachment)
      ))

#+end_src

#+RESULTS:
| distro.tube | :base-directory | ~/nc/gitlab-repos/distro.tube/ | :base-extension | org  | :publishing-directory | ~/nc/gitlab-repos/distro.tube/html/ | :recursive | t    | :exclude | org-html-themes/.* | :publishing-function | org-html-publish-to-html | :headline-levels      |                                  4 | :auto-preamble | t |          |                       |                      |                        |
| org-static  | :base-directory | ~/Dropbox/Org/website/         | :base-extension | css\ | js\                   | png\                                | jpg\       | gif\ | pdf\     | mp3\               | ogg\                 | swf                      | :publishing-directory | ~/Dropbox/Org/website/public_html/ | :recursive     | t | :exclude | .*/org-html-themes/.* | :publishing-function | org-publish-attachment |

* Org-roam
#+begin_src emacs-lisp
(use-package org-roam
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-completion-everywhere t)
  (org-roam-directory "~/Dropbox/Org/Roam/")
  (setq org-roam-node-display-template
      (concat "${type:15} ${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-capture-templates
   '(("d" "default" plain "%?"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+date: %U\n#+EXPORT_FILE_NAME: \n#+filetags: \n#+Reference: ")
      :unnarrowed t)
     ("D" "development" plain
      "* Language: %?\n\n* Reference:\n\n"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+date: %U\n#+filetags: ")
      :unnarrowed t)
     ;; Plantilla RSS integrada
     ("r" "rss reference" plain
      "* Detalles del Artículo\n- **Autor:** %:elfeed-author\n- **Medio:** %:elfeed-feed-title\n- **Fecha Original:** %:elfeed-date\n- **Enlace:** %:elfeed-link\n\n* Notas y Apuntes\n%?"
      :if-new (file+head "%<%Y%m%d%H%M%S>-rss-${slug}.org" 
                         "#+title: ${title}\n#+date: %U\n#+filetags: :rss:reference:\n#+Reference: %:elfeed-link\n")
      :unnarrowed t)
     ("b" "book notes" plain
      "* Book Information
Author: %^{Author}
Title: %^{Book Title}
Year: %^{Year}
Status: %^{Status|Reading|Completed|To Read}
 ,* Summary
%^{Brief summary}
 ,* Notes
%?
"
      :if-new (file+head "%<%Y%m%d%H%M%S>-book-%^{Slug}.org"
                        "#+title: %^{Book Title}\n#+date: %U\n#+filetags: book literature\n#+EXPORT_FILE_NAME: \n#+Reference: \n")
      :unnarrowed t)
     ("B" "book simple" plain
           "* Book Details\n- Author: %^{Author}\n- Year: %^{Year}\n- Status: %^{Status|Reading|Completed|To Read}\n- Rating: %^{Rating}/5\n* Summary\n%^{Brief summary}\n* Key Takeaways\n%?\n* Notes"
           :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+title: ${title}\n#+date: %U\n#+filetags: book\n#+EXPORT_FILE_NAME: \n#+Reference: %a\n")
           :unnarrowed t)
     ("c" "chapter notes" plain
      "* Chapter: %^{Chapter Number/Name}
Book: %^{Book Title}
Pages: %^{Pages}
 ,** Summary
%^{Chapter summary}
 ,** Key Points
%?
 ,** Quotes
 ,** Personal Notes
 ,** Questions/Doubts
 ,** Connections
"
      :if-new (file+head "%<%Y%m%d%H%M%S>-chapter-%^{Chapter Slug}.org"
                        "#+title: %^{Chapter Title}\n#+date: %U\n#+filetags: book chapter notes\n#+EXPORT_FILE_NAME: \n#+Reference: \n")
      :unnarrowed t)
     ("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: Project")
      :unnarrowed t)))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n c" . org-roam-capture)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
         ("C-M-i"    . completion-at-point)
         ("C-c n y" . org-roam-dailies-capture-yesterday)
         ("C-c n t" . org-roam-dailies-capture-tomorrow))
  :config
  (require 'org-roam-dailies)
  (org-roam-setup))

;; Función para limpiar títulos duplicados en archivos existentes
(defun my/fix-duplicate-titles ()
  "Fix duplicate #+title: prefixes in org-roam files"
  (interactive)
  (let ((files (directory-files-recursively org-roam-directory "\\.org$")))
    (dolist (file files)
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (when (re-search-forward "^#\\+title: #+title: \\(.*\\)$" nil t)
          (let ((clean-title (match-string 1)))
            (replace-match (concat "#+title: " clean-title))
            (write-file file)
            (message "Fixed title in: %s" file)))))))

;; Hooks para modos de texto
(add-hook 'text-mode-hook 'turn-on-auto-fill)
(add-hook 'text-mode-hook
          '(lambda () (flyspell-mode 1)))
#+end_src
#+begin_src emacs-lisp
;; =============================================================================
;; CAPTURA DE ELFEED A ORG-ROAM DEFINITIVA (100% DIRECTA SIN MINIBUFFER)
;; =============================================================================

(defun my/elfeed-to-org-roam ()
  "Captura el artículo de Elfeed y crea la nota en Org-roam directamente sin prompts de Vertico."
  (interactive)
  (let* ((entry (if (eq major-mode 'elfeed-show-mode)
                    elfeed-show-entry
                  (elfeed-search-selected :single)))
         (title (elfeed-entry-title entry))
         (link (elfeed-entry-link entry))
         (author (or (elfeed-meta entry :author) "Desconocido"))
         (feed-title (elfeed-feed-title (elfeed-entry-feed entry)))
         (date (format-time-string "%Y-%m-%d %H:%M" (seconds-to-time (elfeed-entry-date entry))))
         ;; Generamos el ID único (UUID) obligatorio que usa Org-roam para indexar nodos
         (org-id (org-id-new))
         ;; SOLUCIÓN: Limpieza de caracteres nativa estándar para crear un slug seguro sin dependencias
         (clean-slug (let ((string (downcase title)))
                       (setq string (replace-regexp-in-string "[^a-z0-9 ]" "" string))
                       (subst-char-in-string ?\s ?_ string)))
         (file-name (format "%s-rss-%s.org" (format-time-string "%Y%m%d%H%M%S") clean-slug))
         (file-path (expand-file-name file-name org-roam-directory)))
    
    ;; Creación e inyección directa del contenido en el archivo sin pasar por plantillas interactivas
    (with-temp-file file-path
      (insert (concat "#+title: " title "\n"
                      "#+date: " (format-time-string "[%Y-%m-%d %a %H:%M]") "\n"
                      "#+filetags: :rss:reference:\n"
                      "#+Reference: " link "\n"
                      ":PROPERTIES:\n"
                      ":ID:       " org-id "\n"
                      ":END:\n\n"
                      "* Detalles del Artículo\n"
                      "- **Autor:** " author "\n"
                      "- **Medio:** " feed-title "\n"
                      "- **Fecha Original:** " date "\n"
                      "- **Enlace:** " link "\n\n"
                      "* Notas y Apuntes\n")))
    
    ;; Abrimos el archivo creado en la pantalla y actualizamos la base de datos de Org-roam en segundo plano
    (find-file file-path)
    (org-roam-db-update-file file-path)
    (goto-char (point-max))
    ;; AUTOMATIZACIÓN: Quitamos la etiqueta 'unread' del artículo en Elfeed
    (elfeed-untag entry 'unread)
    (elfeed-search-update-entry entry) ; Refresca la interfaz visual
    
    (message "Nota de referencia creada y artículo marcado como leído: %s" file-name)))
;; Asignación nativa de la tecla 'R' (Mayúscula + R) dentro de Elfeed
(map! :map elfeed-show-mode-map   :n "R" #'my/elfeed-to-org-roam)
(map! :map elfeed-search-mode-map :n "R" #'my/elfeed-to-org-roam)
#+end_src

#+RESULTS:
| (lambda nil (flyspell-mode 1)) | turn-on-auto-fill | +spell-remove-run-together-switch-for-aspell-h | er/add-text-mode-expansions | visual-line-mode | display-line-numbers-mode | vi-tilde-fringe-mode | text-mode-hook-identify |


* ORG-ROAM-UI

#+begin_src emacs-lisp

(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

#+end_src

#+RESULTS:
: t

* ORG-REF

#+begin_src emacs-lisp

;; config.el
(use-package! org-roam-bibtex
  :after (org-roam org-ref)
  :hook (org-roam-mode . org-roam-bibtex-mode))

(use-package! org-ref
  :after org
  :config
  (setq bibtex-completion-bibliography '("~/Dropbox/Org/refs/biblio.bib")
        bibtex-completion-notes-path "~/Dropbox/Org/refs/astro"
        bibtex-completion-pdf-field "file")

  ;; Función para abrir PDFs (corregida)
  (setq bibtex-completion-pdf-open-function
        (lambda (fpath)
          (call-process "open" nil 0 nil fpath))))

(use-package! ivy-bibtex
  :after (org-ref ivy))


#+end_src

* ORG-CLOCK

#+begin_src emacs-lisp
(after! org
  ;; Guarda el reloj activo e historial al salir de Emacs, y lo carga al iniciar
  (setq org-clock-persist t)
  
  ;; Activa la persistencia del reloj (Esto reemplaza a org-clock-persistence-insinuate)
  (org-clock-persistence-insinuate) ; <-- BORRA ESTA LÍNEA si te vuelve a fallar, la configuración moderna es solo la línea de abajo:
  (org-clock-load)

  ;; Muestra mucho historial para elegir fácilmente en la lista C-F11
  (setq org-clock-history-length 23)

  ;; Reanuda la tarea si el reloj está abierto al hacer clock-in
  (setq org-clock-in-resume t)

  ;; Elimina tareas cronometradas con duración de 0:00
  (setq org-clock-out-remove-zero-time-clocks t)

  ;; Detiene el reloj al mover una tarea a un estado finalizado (DONE)
  (setq org-clock-out-when-done t)

  ;; Incluye la tarea activa actual en los reportes de tiempo
  (setq org-clock-report-include-clocking-task t))
#+end_src
* ORG-CONTACTS
#+begin_src emacs-lisp :tangle no
(use-package org-contacts
  :after org
  :custom
  (org-contacts-files '("~/Dropbox/Org/Agenda/contactos.org")))
#+end_src


** Org-auto-tangle

#+begin_src emacs-lisp
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))
#+end_src

* PASSWORD STORE
Uses the standard Unix password store "pass".

#+begin_src emacs-lisp
(use-package! password-store)
#+end_src

* PERSPECTIVE
Perspective provides multiple named workspaces (or "perspectives") in Emacs, similar to having multiple desktops in window managers like Awesome and XMonad.  Each perspective has its own buffer list and its own window layout, making it easy to work on many separate projects without getting lost in all the buffers.  Switching to a perspective activates its window configuration, and when in a perspective, only its buffers are available (by default).  Doom Emacs uses 'SPC some_key' for binding some of the perspective commands, so I used this binging format for the perspective bindings that I created..

| COMMAND                    | DESCRIPTION                         | KEYBINDING |
|----------------------------+-------------------------------------+------------|
| persp-switch               | Switch to perspective NAME          | SPC DEL    |
| persp-switch-to-buffer     | Switch to buffer in perspective     | SPC ,      |
| persp-next                 | Switch to next perspective          | SPC ]      |
| persp-prev                 | Switch to previous perspective      | SPC [      |
| persp-add-buffer           | Add a buffer to current perspective | SPC +      |
| persp-remove-by-name       | Remove perspective by name          | SPC -      |
| +workspace/switch-to-{0-9} | Switch to workspace /n/               | SPC 0-9    |

#+begin_src emacs-lisp
(map! :leader
      :desc "Switch to perspective NAME" "DEL" #'persp-switch
      :desc "Switch to buffer in perspective" "," #'persp-switch-to-buffer
      :desc "Switch to next perspective" "]" #'persp-next
      :desc "Switch to previous perspective" "[" #'persp-prev
      :desc "Add a buffer current perspective" "+" #'persp-add-buffer
      :desc "Remove perspective by name" "-" #'persp-remove-by-name)
#+end_src

* RAINBOW MODE
Rainbox mode displays the actual color for any hex value color.  It's such a nice feature that I wanted it turned on all the time, regardless of what mode I am in.  The following creates a global minor mode for rainbow-mode and enables it.

#+begin_src emacs-lisp
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda () (rainbow-mode 1)))
(global-rainbow-mode 1 )
#+end_src

* REGISTERS
Emacs registers are compartments where you can save text, rectangles and positions for later use. Once you save text or a rectangle in a register, you can copy it into the buffer once or many times; once you save a position in a register, you can jump back to that position once or many times.  The default GNU Emacs keybindings for these commands (with the exception of counsel-register) involves 'C-x r' followed by one or more other keys.  I wanted to make this a little more user friendly, and since I am using Doom Emacs, I choose to replace the 'C-x r' part of the key chords with 'SPC r'.

| COMMAND                          | DESCRIPTION                      | KEYBINDING |
|----------------------------------+----------------------------------+------------|
| copy-to-register                 | /Copy to register/                 | SPC r c    |
| frameset-to-register             | /Frameset to register/             | SPC r f    |
| insert-register                  | /Insert contents of register/      | SPC r i    |
| jump-to-register                 | /Jump to register/                 | SPC r j    |
| list-registers                   | /List registers/                   | SPC r l    |
| number-to-register               | /Number to register/               | SPC r n    |
| counsel-register                 | /Interactively choose a register/  | SPC r r    |
| view-register                    | /View a register/                  | SPC r v    |
| window-configuration-to-register | /Window configuration to register/ | SPC r w    |
| increment-register               | /Increment register/               | SPC r +    |
| point-to-register                | /Point to register/                | SPC r SPC  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("r" . "registers")
       :desc "Copy to register" "c" #'copy-to-register
       :desc "Frameset to register" "f" #'frameset-to-register
       :desc "Insert contents of register" "i" #'insert-register
       :desc "Jump to register" "j" #'jump-to-register
       :desc "List registers" "l" #'list-registers
       :desc "Number to register" "n" #'number-to-register
       :desc "Interactively choose a register" "r" #'counsel-register
       :desc "View a register" "v" #'view-register
       :desc "Window configuration to register" "w" #'window-configuration-to-register
       :desc "Increment register" "+" #'increment-register
       :desc "Point to register" "SPC" #'point-to-register))
#+end_src

* SHELLS
Settings for the various shells and terminal emulators within Emacs.
+ 'shell-file-name' -- sets the shell to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm.
+ 'eshell-aliases-file' -- sets an aliases file for the eshell.

#+begin_src emacs-lisp
(setq shell-file-name "/bin/zsh"
      vterm-max-scrollback 5000)
(setq eshell-rc-script "~/.config/doom/eshell/profile"
      eshell-aliases-file "~/.config/doom/eshell/aliases"
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
(map! :leader
      :desc "Eshell" "e s" #'eshell
      :desc "Eshell popup toggle" "e t" #'+eshell/toggle
      :desc "Counsel eshell history" "e h" #'counsel-esh-history
      :desc "Vterm popup toggle" "v t" #'+vterm/toggle)
#+end_src

* SPELL-FU
#+begin_src emacs-lisp
;; ;; Configuración de ispell/aspell ANTES de spell-fu
;; (setq ispell-program-name "aspell")
;; (setq ispell-extra-args '("--sug-mode=ultra" "--encoding=utf-8"))
;; (setq ispell-dictionary "spanish")

;; ;; Forzar UTF-8 como encoding para el proceso
;; (setq ispell-process-coding-system 'utf-8-unix)

;; ;; Ahora tu configuración de spell-fu
;;  (use-package spell-fu)
;;  (global-spell-fu-mode)

;;  (add-hook 'spell-fu-mode-hook
;;   (lambda ()
;;     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "spanish"))
;;     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "es"))
;;     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "en"))
;;     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "it"))
;;     (spell-fu-dictionary-add
;;       (spell-fu-get-personal-dictionary "es-personal" "~/.aspell.es.pws"))
;;     (spell-fu-dictionary-add
;;       (spell-fu-get-personal-dictionary "en-personal" "~/.aspell.en.pws"))
;;     (spell-fu-dictionary-add
;;       (spell-fu-get-personal-dictionary "it-personal" "~/.aspell.it.pws"))))
 #+end_src

 #+begin_src emacs-lisp

 (use-package spell-fu)
 (global-spell-fu-mode)

 (add-hook 'spell-fu-mode-hook
   (lambda ()
     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "spanish"))
     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "es"))
     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "en"))
     (spell-fu-dictionary-add (spell-fu-get-ispell-dictionary "it"))
     (spell-fu-dictionary-add
       (spell-fu-get-personal-dictionary "es-personal" "~/ezequiel/.aspell.es.pws"))
     (spell-fu-dictionary-add
       (spell-fu-get-personal-dictionary "en-personal" "~/ezequiel/.aspell.en.pws"))
     (spell-fu-dictionary-add
       (spell-fu-get-personal-dictionary "it-personal" "~/ezequiel/.aspell.it.pws"))))
 (setq ispell-dictionary "spanish")

 #+end_src
* SPLITS
I set splits to default to opening on the right using 'prefer-horizontal-split'.  I set a keybinding for 'clone-indirect-buffer-other-window' for when I want to have the same document in two splits.  The text of the indirect buffer is always identical to the text of its base buffer; changes made by editing either one are visible immediately in the other.  But in all other respects, the indirect buffer and its base buffer are completely separate.  For example, I can fold one split but other will be unfolded.

#+begin_src emacs-lisp
(defun prefer-horizontal-split ()
  (set-variable 'split-height-threshold nil t)
  (set-variable 'split-width-threshold 40 t)) ; make this as low as needed
(add-hook 'markdown-mode-hook 'prefer-horizontal-split)
(map! :leader
      :desc "Clone indirect buffer other window" "b c" #'clone-indirect-buffer-other-window)
#+end_src

* WINNER MODE
Winner mode has been included with GNU Emacs since version 20.  This is a global minor mode and, when activated, it allows you to “undo” (and “redo”) changes in the window configuration with the key commands 'SCP w <left>' and 'SPC w <right>'.

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("w" . "window")
       :desc "Winner redo" "<right>" #'winner-redo
       :desc "Winner undo" "<left>" #'winner-undo))
#+end_src

* WRITEROOM MODE
Writeroom mode is a minor mode for Emacs that implements a distraction-free writing mode.

#+begin_src emacs-lisp
(use-package! writeroom-mode)
(with-eval-after-load 'writeroom-mode
  (define-key writeroom-mode-map (kbd "C-M-<") #'writeroom-decrease-width)
  (define-key writeroom-mode-map (kbd "C-M->") #'writeroom-increase-width)
  (define-key writeroom-mode-map (kbd "C-M-=") #'writeroom-adjust-width))

(advice-add 'text-scale-adjust :after
  #'visual-fill-column-adjust)

(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("w" . "writeroom")
        :desc "enable/disable writeroom" "w" #'writeroom-mode)
       (:prefix ("f" . "focus-mode")
        :desc "enabledisable focus-mode" "f" #'focus-mode)
      (:prefix ("d" . "doom-big-font-mode")
        :desc "enable doom-big-font-mode" "f" #'doom-big-font-mode)))

#+end_src

#+RESULTS:
: winner-undo


* ZAP TO CHAR
Emacs provides a 'zap-to-char' command that kills from the current point to a character.  It is bound to 'M-z' in standard GNU Emacs but since Doom Emacs uses 'SPC' as its leader key and does not have 'SPC z' binded to anything, it just makes since to use it for 'zap-to-char'.  Note that 'zap-to-char' can be used with the universal argument 'SPC u' to modify its behavior.  Examples of 'zap-to-char' usage are listed in the table below:

| KEYBINDING                | WHAT IS DOES                                               |
|---------------------------+------------------------------------------------------------|
| SPC z e                   | deletes all chars to the next occurrence of 'e'            |
| SPC u 2 SPC z e           | deletes all chars to the second occurrence of 'e'          |
| SPC u - SPC z e           | deletes all chars to the previous occurrence of 'e'        |
| SPC u - 2 SPC z e         | deletes all chars to the second previous occurrence of 'e' |
| SPC u 1 0 0 SPC u SPC z e | deletes all chars to the 100th occurrence of 'e'           |

=TIP=: The universal argument (SPC u) can only take a single integer by default.  If you need to use a multi-digit number (like 100 in the last example in the table above), then you must terminate the universal argument with another 'SPC u' after typing the number.

'zap-up-to-char' is an alternative command that does not zap the char specified.  It is binded to 'SPC Z'.  It can also be used in conjunction with the universal argument 'SPC u' in similar fashion to the the 'zap-to-char' examples above.

=NOTE=:  Vim (evil mode) has similar functionality builtin.  You can delete to the next occurrence of 'e' by using 'dte' in normal.  To delete to the next occurrence of 'e' including the 'e', then you would use 'dfe'.  And you can modify 'dt' and 'df' by prefixing them with numbers, so '2dte' would delete to the second occurrence of 'e'.

#+begin_src emacs-lisp
(map! :leader
      :desc "Zap to char" "z" #'zap-to-char
      :desc "Zap up to char" "Z" #'zap-up-to-char)
#+end_src

* PYTHON

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)))
#+end_src

* PHP Configuration with Intelephense

** LSP Configuration
#+begin_src emacs-lisp
(use-package! lsp-mode
  :hook (php-mode . lsp-deferred)
  :commands (lsp lsp-deferred)
  :config
  (setq lsp-prefer-flymake nil
        lsp-enable-symbol-highlighting t
        lsp-enable-snippet t))
#+end_src

** LSP UI
#+begin_src emacs-lisp
(use-package! lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :config
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-position 'top
        lsp-ui-sideline-enable t
        lsp-ui-sideline-show-hover nil
        lsp-ui-peek-enable t))
#+end_src

** Intelephense Configuration
#+begin_src emacs-lisp
(after! lsp-mode
  (setq lsp-intelephense-multi-root nil ; don't scan unrelated projects
        lsp-intelephense-files-max-size 5000000
        lsp-intelephense-format-braces "k&r"
        lsp-intelephense-completion-insert-use-declaration t
        lsp-intelephense-completion-fully-qualify-global-constants-and-functions nil
        lsp-intelephense-rename-exclude-vendor-directories t
        lsp-intelephense-diagnostics-enable t
        ;; Definí INTELEPHENSE_LICENSE_KEY en tu .zshrc/.bashrc en vez de
        ;; hardcodear la clave acá (evita exponerla si subís el dotfile).
        lsp-intelephense-licence-key (getenv "INTELEPHENSE_LICENSE_KEY")
        lsp-intelephense-stub-directories
        '("apache" "bcmath" "bz2" "calendar" "com_dotnet" "Core" "ctype" "curl" "date"
          "dba" "dom" "enchant" "exif" "fileinfo" "filter" "fpm" "ftp" "gd" "hash"
          "iconv" "imap" "interbase" "intl" "json" "ldap" "libxml" "mbstring" "mcrypt"
          "meta" "mssql" "mysql" "mysqli" "oci8" "odbc" "openssl" "pcntl" "pcre" "PDO"
          "pdo_ibm" "pdo_mysql" "pdo_pgsql" "pdo_sqlite" "pgsql" "Phar" "posix" "pspell"
          "readline" "recode" "Reflection" "regex" "session" "shmop" "SimpleXML" "snmp"
          "soap" "sockets" "sodium" "SPL" "sqlite3" "standard" "superglobals" "sybase"
          "sysvmsg" "sysvsem" "sysvshm" "tidy" "tokenizer" "wddx" "xml" "xmlreader"
          "xmlrpc" "xmlwriter" "Zend OPcache" "zip" "zlib")))
#+end_src

** PHP Mode Hooks
#+begin_src emacs-lisp
(add-hook! php-mode
  (setq-local lsp-diagnostics-provider :flycheck)
  (setq-local flycheck-phpcs-standard "PSR12")
  (setq-local tab-width 4)
  (setq-local c-basic-offset 4)
  (setq-local indent-tabs-mode nil))
#+end_src

** Company Configuration for PHP
#+begin_src emacs-lisp
(after! company
  (setq company-idle-delay 0.2
        company-minimum-prefix-length 1
        company-tooltip-limit 10
        company-dabbrev-downcase nil
        company-dabbrev-ignore-case nil
        company-dabbrev-code-other-buffers t
        company-tooltip-align-annotations t))
#+end_src

** Flycheck PHP Configuration
#+begin_src emacs-lisp
(after! flycheck
  (flycheck-add-mode 'php 'php-mode)
  (flycheck-add-mode 'php-phpmd 'php-mode)
  (flycheck-add-mode 'php-phpcs 'php-mode))
#+end_src

** Laravel Blade Configuration
#+begin_src emacs-lisp
;; Instalación de web-mode para Blade templates
(use-package! web-mode
  :mode (("\\.blade\\.php\\'" . web-mode))
  :config
  (setq web-mode-markup-indent-offset 2
        web-mode-css-indent-offset 2
        web-mode-code-indent-offset 2
        web-mode-enable-auto-pairing t
        web-mode-enable-auto-expanding t
        web-mode-enable-css-colorization t
        web-mode-enable-auto-closing t
        web-mode-enable-auto-quoting t))

;; Configuración específica para archivos Blade
(add-to-list 'auto-mode-alist '("\\.blade\\.php\\'" . web-mode))

;; Hook para Blade files
(add-hook 'web-mode-hook
  (lambda ()
    (when (string-match-p "\\.blade\\.php\\'" (buffer-file-name))
      (setq web-mode-enable-blade-detection t)
      (setq web-mode-engines-alist '(("blade" . "\\.blade\\.php\\'"))))))
#+end_src

** Laravel Artisan Commands
#+begin_src emacs-lisp
(defun laravel-artisan (command)
  "Run Laravel Artisan command."
  (interactive "sArtisan command: ")
  (let ((default-directory (projectile-project-root)))
    (compilation-start (concat "php artisan " command) nil
                      (lambda (mode) "*Laravel Artisan*"))))

(defun laravel-tinker ()
  "Start Laravel Tinker REPL."
  (interactive)
  (let ((default-directory (projectile-project-root)))
    (term "php artisan tinker")))

(defun laravel-migrate ()
  "Run Laravel migrations."
  (interactive)
  (laravel-artisan "migrate"))

(defun laravel-migrate-fresh ()
  "Run fresh Laravel migrations."
  (interactive)
  (laravel-artisan "migrate:fresh"))

(defun laravel-serve ()
  "Start Laravel development server."
  (interactive)
  (laravel-artisan "serve"))

;; Key bindings for Laravel
(map! :after php-mode
      :localleader
      :map php-mode-map
      :prefix ("l" . "Laravel")
      "a" #'laravel-artisan
      "t" #'laravel-tinker
      "m" #'laravel-migrate
      "M" #'laravel-migrate-fresh
      "s" #'laravel-serve)
#+end_src

** Laravel Yasnippet Configuration
#+begin_src emacs-lisp
(after! yasnippet
  (setq yas-snippet-dirs (delete-dups (append yas-snippet-dirs '("~/.config/doom/snippets")))))
#+end_src

** Laravel Project Detection
#+begin_src emacs-lisp
(defun is-laravel-project ()
  "Check if current project is a Laravel project."
  (and (projectile-project-p)
       (file-exists-p (concat (projectile-project-root) "artisan"))))

(defun laravel-project-setup ()
  "Setup Laravel specific configurations when in a Laravel project."
  (when (is-laravel-project)
    (setq-local lsp-intelephense-files-exclude
                ["**/node_modules/**" "**/vendor/**" "**/storage/**"
                 "**/bootstrap/cache/**" "**/public/storage/**"])
    (setq-local lsp-intelephense-stub-directories
                (append lsp-intelephense-stub-directories '("laravel")))))

(add-hook 'php-mode-hook #'laravel-project-setup)
#+end_src

** WordPress Configuration
#+begin_src emacs-lisp
(defun is-wordpress-project ()
  "Check if current project is a WordPress project."
  (and (projectile-project-p)
       (or (file-exists-p (concat (projectile-project-root) "wp-config.php"))
           (file-exists-p (concat (projectile-project-root) "wp-config-sample.php"))
           (file-exists-p (concat (projectile-project-root) "wp-load.php")))))

(defun wordpress-project-setup ()
  "Setup WordPress specific configurations."
  (when (is-wordpress-project)
    (setq-local lsp-intelephense-files-exclude
                ["**/node_modules/**" "**/wp-admin/**" "**/wp-includes/**"])
    (setq-local lsp-intelephense-stub-directories
                (append lsp-intelephense-stub-directories
                        '("wordpress" "woocommerce" "acf-pro" "polylang")))
    ;; WordPress coding standards
    (setq-local flycheck-phpcs-standard "WordPress")
    (setq-local indent-tabs-mode t)
    (setq-local tab-width 4)))

(add-hook 'php-mode-hook #'wordpress-project-setup)
#+end_src

** WordPress Helper Functions
#+begin_src emacs-lisp
(defun wp-create-hook (hook-name function-name priority)
  "Insert WordPress add_action or add_filter."
  (interactive "sHook name: \nsFuction name: \nnPriority (default 10): ")
  (let ((priority (if (= priority 0) 10 priority)))
    (insert (format "add_action('%s', '%s', %d);" hook-name function-name priority))))

(defun wp-create-shortcode (shortcode-name function-name)
  "Insert WordPress shortcode registration."
  (interactive "sShortcode name: \nsFunction name: ")
  (insert (format "add_shortcode('%s', '%s');" shortcode-name function-name)))

(defun wp-enqueue-script ()
  "Insert wp_enqueue_script template."
  (interactive)
  (insert "wp_enqueue_script(\n    'handle',\n    get_template_directory_uri() . '/path/to/script.js',\n    array('jquery'),\n    '1.0.0',\n    true\n);"))

(defun wp-enqueue-style ()
  "Insert wp_enqueue_style template."
  (interactive)
  (insert "wp_enqueue_style(\n    'handle',\n    get_template_directory_uri() . '/path/to/style.css',\n    array(),\n    '1.0.0'\n);"))

;; WordPress key bindings
(map! :after php-mode
      :localleader
      :map php-mode-map
      :prefix ("w" . "WordPress")
      "h" #'wp-create-hook
      "s" #'wp-create-shortcode
      "j" #'wp-enqueue-script
      "c" #'wp-enqueue-style)
#+end_src

** Stubs adicionales (Laravel, WordPress, librerías comunes)
#+begin_src emacs-lisp
(after! lsp-mode
  (setq lsp-intelephense-stub-directories
        (append lsp-intelephense-stub-directories
                '("wordpress" "woocommerce" "acf-pro" "polylang" "laravel"
                  "phpunit" "mockery" "guzzle" "symfony" "doctrine"))))
#+end_src

** Instalar stubs de terceros (comandos manuales, no se tanglean)
#+begin_src bash :tangle no
composer global require barryvdh/laravel-ide-helper
composer global require --dev barryvdh/laravel-debugbar
wp package install wp-cli/php-stubs-generator
#+end_src

** Configuración Específica por Proyecto (referencia, no se tanglea)
*** Para proyectos Laravel (.dir-locals.el)
#+begin_src emacs-lisp :tangle no
((php-mode . ((lsp-intelephense-files-exclude .
["**/node_modules/**" "**/vendor/**" "**/storage/**"
 "**/bootstrap/cache/**" "**/public/storage/**"])
(flycheck-phpcs-standard . "PSR12")
(indent-tabs-mode . nil)
(tab-width . 4)))
(web-mode . ((web-mode-markup-indent-offset . 2)
(web-mode-css-indent-offset . 2)
(web-mode-code-indent-offset . 2))))
#+end_src

*** Para proyectos WordPress (.dir-locals.el)
#+begin_src emacs-lisp :tangle no
((php-mode . ((lsp-intelephense-files-exclude .
["**/node_modules/**" "**/wp-admin/**" "**/wp-includes/**"])
(flycheck-phpcs-standard . "WordPress")
(indent-tabs-mode . t)
(tab-width . 4))))
#+end_src

** Crear directorios de snippets (comando manual, no se tanglea)
#+begin_src bash :tangle no
mkdir -p ~/.config/doom/snippets/php-mode
mkdir -p ~/.config/doom/snippets/web-mode
#+end_src

** PHPUnit
#+begin_src emacs-lisp
(use-package! phpunit
  :config
  (setq phpunit-switches "--colors=always")
  (map! :after php-mode
        :localleader
        :map php-mode-map
        :prefix ("u" . "PHPUnit")
        "u" #'phpunit-run
        "p" #'phpunit-popup
        "f" #'phpunit-run-at-point
        "c" #'phpunit-class))
#+end_src

** Composer
#+begin_src emacs-lisp
(use-package! composer
  :after php-mode
  :commands (composer composer-install composer-update composer-require
             composer-require-dev composer-dump-autoload composer-run-script)
  :config
  (setq composer-executable "composer")

  (defun is-composer-project ()
    "Check if current project has a composer.json."
    (and (projectile-project-p)
         (file-exists-p (concat (projectile-project-root) "composer.json"))))

  (defun composer-project-setup ()
    "Enable composer-file-mode when in a composer project."
    (when (is-composer-project)
      (composer-file-mode 1)))

  (add-hook 'php-mode-hook #'composer-project-setup)

  (map! :localleader
        :map php-mode-map
        :prefix ("c" . "Composer")
        "i" #'composer-install
        "u" #'composer-update
        "r" #'composer-require
        "R" #'composer-require-dev
        "d" #'composer-dump-autoload
        "s" #'composer-run-script))
#+end_src

** Soporte para archivos .env (Laravel, etc.)
#+begin_src emacs-lisp
(use-package! dotenv-mode
  :mode "\\.env\\..*\\'")
#+end_src

** [OPCIONAL] PHP-CS-Fixer al guardar
;; Requiere: composer global require friendsofphp/php-cs-fixer
;; y que "php-cs-fixer" esté en tu PATH (mismo tema que resolvimos con intelephense).
;; Descomentá este bloque si querés formateo automático al guardar.
#+begin_src emacs-lisp :tangle no
(use-package! reformatter
  :config
  (reformatter-define php-cs-fixer-format
    :program "php-cs-fixer"
    :args '("fix" "--rules=@PSR12" input-file)))

(add-hook 'php-mode-hook
  (lambda ()
    (add-hook 'before-save-hook #'php-cs-fixer-format-buffer nil t)))
#+end_src

* PYTHON CONFIGURATION (Finance / Jupyter)

** Pyright / LSP
#+begin_src emacs-lisp
(after! lsp-pyright
  (setq lsp-pyright-multi-root nil
        lsp-pyright-auto-import-completions t
        lsp-pyright-typechecking-mode "basic"))
#+end_src

** Virtualenvs con pyvenv
#+begin_src emacs-lisp
(use-package! pyvenv
  :after python
  :config
  (setq pyvenv-default-virtual-env-name ".venv")
  (pyvenv-mode 1)
  (setq pyvenv-mode-line-indicator
        '(pyvenv-virtual-env-name ("[venv:" pyvenv-virtual-env-name "] "))))

;; Auto-activar el venv del proyecto al abrir un .py
(defun my/pyvenv-autoload ()
  "Activa automáticamente el venv .venv o venv/ en la raíz del proyecto."
  (when (projectile-project-p)
    (let* ((root (projectile-project-root))
           (venv-dot (expand-file-name ".venv" root))
           (venv-plain (expand-file-name "venv" root)))
      (cond
       ((file-directory-p venv-dot) (pyvenv-activate venv-dot))
       ((file-directory-p venv-plain) (pyvenv-activate venv-plain))))))

(add-hook 'python-mode-hook #'my/pyvenv-autoload)
#+end_src

** Variables de entorno (.env) con direnv
#+begin_src emacs-lisp
(use-package! envrc
  :hook (after-init . envrc-global-mode))
#+end_src

** Instalar dependencias dentro del venv activo
#+begin_src emacs-lisp
(defun python-pip-install (package)
  "Instala PACKAGE con pip en el venv activo (pyvenv)."
  (interactive "sPaquete a instalar: ")
  (unless pyvenv-virtual-env
    (user-error "No hay ningún venv activo. Activalo primero con pyvenv-activate"))
  (let ((default-directory (or (projectile-project-root) default-directory)))
    (compile (format "pip install %s" package))))

(defun python-pip-install-requirements ()
  "Instala desde requirements.txt en el venv activo."
  (interactive)
  (unless pyvenv-virtual-env
    (user-error "No hay ningún venv activo. Activalo primero con pyvenv-activate"))
  (let ((default-directory (or (projectile-project-root) default-directory)))
    (compile "pip install -r requirements.txt")))

(defun python-pip-freeze ()
  "Actualiza requirements.txt con lo instalado en el venv activo."
  (interactive)
  (unless pyvenv-virtual-env
    (user-error "No hay ningún venv activo. Activalo primero con pyvenv-activate"))
  (let ((default-directory (or (projectile-project-root) default-directory)))
    (shell-command "pip freeze > requirements.txt")
    (message "requirements.txt actualizado")))

(map! :after python
      :localleader
      :map python-mode-map
      :prefix ("v" . "Venv/Pip")
      "a" #'pyvenv-activate
      "d" #'pyvenv-deactivate
      "w" #'pyvenv-workon
      "i" #'python-pip-install
      "r" #'python-pip-install-requirements
      "f" #'python-pip-freeze)
#+end_src

** Jupyter notebooks (kernels reales)
#+begin_src emacs-lisp
(use-package! jupyter
  :after python
  :commands (jupyter-run-repl jupyter-connect-repl)
  :config
  (setq jupyter-repl-echo-eval-p t))

(map! :after python
      :localleader
      :map python-mode-map
      :prefix ("j" . "Jupyter")
      "j" #'jupyter-run-repl
      "c" #'jupyter-connect-repl
      "e" #'jupyter-eval-line-or-region
      "b" #'jupyter-eval-buffer)
#+end_src

** Notebooks estilo celda en archivos .py (# %%)
#+begin_src emacs-lisp
(use-package! code-cells
  :hook (python-mode . code-cells-mode)
  :config
  (map! :map code-cells-mode-map
        :localleader
        :prefix ("n" . "Notebook cells")
        "n" #'code-cells-eval
        "j" #'code-cells-forward-cell
        "k" #'code-cells-backward-cell))
#+end_src

** Virtualenvs con pyvenv
#+begin_src emacs-lisp
(use-package! pyvenv
  :after python
  :config
  (setq pyvenv-mode-line-indicator
        '(pyvenv-virtual-env-name ("[venv:" pyvenv-virtual-env-name "] "))))

(defvar my/pyvenv-default-shared "~/.venvs/finanzas"
  "Venv compartido a usar cuando el proyecto no tiene uno propio.")

(defun my/pyvenv-autoload ()
  "Activa el venv local del proyecto (.venv o venv/) si existe;
si no, cae al venv compartido `my/pyvenv-default-shared'."
  (let* ((root (or (and (projectile-project-p) (projectile-project-root))
                    default-directory))
         (venv-dot (expand-file-name ".venv" root))
         (venv-plain (expand-file-name "venv" root)))
    (cond
     ((file-directory-p venv-dot) (pyvenv-activate venv-dot))
     ((file-directory-p venv-plain) (pyvenv-activate venv-plain))
     ((file-directory-p (expand-file-name my/pyvenv-default-shared))
      (pyvenv-activate (expand-file-name my/pyvenv-default-shared)))
     (t (message "No se encontró venv local ni compartido")))))

(add-hook 'python-mode-hook #'my/pyvenv-autoload)
#+end_src

** EIN (Emacs IPython Notebook)

#+begin_src emacs-lisp
(use-package! ein
  :commands (ein:run ein:login ein:notebooklist-open)
  :config
  (setq ein:output-area-inlined-images t)) ; gráficos inline (matplotlib, etc.)

(map! :leader
      :prefix ("n" . "Notebooks")
      "n" #'ein:notebooklist-open
      "r" #'ein:run)
#+end_src

** Cómo usar EIN (ayuda memoria)
#+begin_comment
FLUJO PARA ABRIR NOTEBOOKS (.ipynb) CON EIN
============================================

Paso 1 — Arrancar el servidor de Jupyter (con el venv activado):

    source ~/.venvs/finanzas/bin/activate
    jupyter notebook --no-browser

  Esto tira una URL con token en la terminal, algo como:
    http://localhost:8888/?token=abc123...

Paso 2 — Desde Emacs, conectarse a ese servidor:

    SPC n n
    (o M-x ein:notebooklist-open)

  Pide la URL — pegar http://localhost:8888/
  (o http://127.0.0.1:8888/, según cómo haya arrancado) y el token si lo pide.

  Aparece la lista de notebooks de esa carpeta (clase4.ipynb, etc.).
  Enter sobre el que se quiera abrir, y se abre con celdas editables.

Alternativa — que EIN arranque el servidor solo (sin terminal aparte):

    M-x ein:run

  Pide la ruta del directorio con los notebooks y el ejecutable de jupyter.

COMANDOS DENTRO DE UN NOTEBOOK ABIERTO:

  C-c C-c   → ejecutar la celda actual
  C-c C-b   → ejecutar todas las celdas de abajo
  M-RET     → ejecutar celda y saltar a la siguiente
  C-c C-t   → insertar celda nueva
  C-x C-s   → guardar el notebook (.ipynb, compatible con Jupyter normal)
#+end_comment

(after! elfeed
  (setq elfeed-search-title-max-width 100)) ; Ajusta el número (100) según el ancho de tu monitor
